### ISSUE TITLE
Pick specific folder for pre-generation

### ISSUE THREAD

**Issue by stueja** [nextcloud/previewgenerator#114]
Just like the `occ files:scan --path="/user/files/subfolder"`command I'd like to see something similar in previewgenerator.
Reason: recently, I dumped 400GB of photos into nextcloud. `files:scan user` would error out with a memory message. I solved that by using `find user/files/pictures/ -maxdepth 1 -mindepth 1 -type d -exec echo {} \; -exec sudo -u http php /usr/share/webapps/nextcloud/occ files:scan --path="/{}" \;`
Having the `--path` possibility in previewgenerator would allow me to chunk down the to-be-generated previews.

**Comment by DKlemann** [comment]
I also see great use in such a feature.

And: It seems like such a functionality technically exists.
In lib/Command/Generate.php, there is a function generatePathPreviews, which does just that, if I understand it correctly (I have next to no PHP experience). It gets called if the execute function in turn gets called which an option "path" as input parameter. I don't know how to pass this option to the function call, though.
The user gets passed as **parameter** "user_id" inside the input parameter.

Maybe something like "path=/<path>" is working already?

**Comment by DKlemann** [comment]
Ok, I just saw in the version history that it was added on June 12th and committed on August 23rd.
The syntax should be:
occ preview:generate-all --path="<path>" <user>

I will try to update my local version.

**Comment by DKlemann** [comment]
Alright, it did work when I updated Generate.php to the newest version (unfortunately, it is not yet available in the Nextcloud app store).

Two points to consider:
1. At the end of line 86, a ")" is missing.
2. I haven't figured out yet how to pass paths with spaces in them.

**Comment by fermulator** [comment]
confirmed today this works (22.2.6, pvg=4.0.0); but I couldn't figure out how to even use it (undocumented onreadme)
got it working though with the above tips, 
`preview:generate-all -vvv --path <username>/files/Family/Photos`
note that Family/Photos for me is an external mount, but Nextcloud pvg doesn't care (:heavy_check_mark: )

**Comment by fermulator** [comment]
it's worth noting also that if the user specified as _invalid_ path for path, the tool just "exits" silently without any error or usage help

**Comment by st3iny** [comment]
I'll see what I can do to improve the documentation around this.

**Comment by st3iny** [comment]
Closing in favor of #144.
