### ISSUE TITLE
Feature Request: Support for Ebooks

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/previewgenerator#117]
EPUB, CBR and CBZ files as supported as in https://apps.nextcloud.com/apps/files_reader

**Comment by Gatak** [comment]
I was looking for the same thing. The eBook reader is implemented in js so maybe it cant work easily on the server end? It would be a major milestone for me as I read a lot of ebooks. :)

**Comment by gennaios** [comment]
Me too. Mainly for EPUB. It has been done before: 

https://github.com/Yetangitu/owncloud-apps/tree/master/files_opds/lib

Not too familiar with the API or PHP. I've tried updating it but no luck so far. I imagine for you it wouldn't be too difficult. Just a question of time and if you feel it is worth doing. 

For EPUB, it is a ZIP file. After parsing a few metadata files, the cover can then be determined and extracted. There could be variation in how makers specify the cover. Not all follow the spec or implement it properly, e.g. some may just have the cover as the first page without specifying the metadata that it is a cover. Yet just the standard case would be good enough.

**Comment by joshtrichards** [comment]
Wouldn't this be implemented outside of `previewgenerator`? This app - despite perhaps its ambiguous name - doesn't literally generate the previews. It only *pre-generates* supported/configured previews. It still relies on NC's built-in preview functionality (which can also be extended by other apps).

Not incidentally, those on this thread may want to go give feedback here: nextcloud/server#39085

**Comment by st3iny** [comment]
Good point! I'm closing this in favor of https://github.com/nextcloud/server/issues/39085.
