### ISSUE TITLE
 Create preview problem "No create permission for folder"

### ISSUE THREAD

**Issue by WikiIUT** [nextcloud/previewgenerator#121]
Hello,
when running whit www user :
`php occ preview:pre-generate`
the app's stop and the error is : 

> 2018-07-17T21:18:26+00:00
> 2018-07-17T21:18:26+00:00   [OCP\Files\NotPermittedException]
> 2018-07-17T21:18:26+00:00   No create permission for folder
> 2018-07-17T21:18:26+00:00
> 2018-07-17T21:18:26+00:00

System is UCS with NC13.04
using

AD integration with Windows Server 2012R2
I have test, modify the permission to the folder to 777, and not resolve the problem,

Thanks for the read,

**Comment by loelkes** [comment]
I have the same issue, currently using NC 16.0.4 and Version 2.1.0 of the app.

Running `preview:generate-all` runs without issue but `preview:pre-generate` fails **immediately** with the mentioned error. Setting the loglevel to `-vvv`gives the following output:

```
September 04, 2019 14:22:32
September 04, 2019 14:22:32 In Folder.php line 162:
September 04, 2019 14:22:32
September 04, 2019 14:22:32   [OCP\Files\NotPermittedException]
September 04, 2019 14:22:32   Could not create folder
September 04, 2019 14:22:32
September 04, 2019 14:22:32
September 04, 2019 14:22:32 Exception trace:
September 04, 2019 14:22:32  () at /srv/nextcloud/www/lib/private/Files/Node/Folder.php:162
September 04, 2019 14:22:32  OC\Files\Node\Folder->newFolder() at /srv/nextcloud/www/lib/private/Files/Node/Root.php:381
September 04, 2019 14:22:32  OC\Files\Node\Root->getUserFolder() at n/a:n/a
September 04, 2019 14:22:32  call_user_func_array() at /srv/nextcloud/www/lib/private/Files/Node/LazyRoot.php:64
September 04, 2019 14:22:32  OC\Files\Node\LazyRoot->__call() at /srv/nextcloud/www/lib/private/Files/Node/LazyRoot.php:281
September 04, 2019 14:22:32  OC\Files\Node\LazyRoot->getUserFolder() at /srv/nextcloud/www/apps/previewgenerator/lib/Command/PreGenerate.php:178
September 04, 2019 14:22:32  OCA\PreviewGenerator\Command\PreGenerate->processRow() at /srv/nextcloud/www/apps/previewgenerator/lib/Command/PreGenerate.php:164
September 04, 2019 14:22:32  OCA\PreviewGenerator\Command\PreGenerate->startProcessing() at /srv/nextcloud/www/apps/previewgenerator/lib/Command/PreGenerate.php:132
September 04, 2019 14:22:32  OCA\PreviewGenerator\Command\PreGenerate->execute() at /srv/nextcloud/www/3rdparty/symfony/console/Command/Command.php:255
September 04, 2019 14:22:32  Symfony\Component\Console\Command\Command->run() at /srv/nextcloud/www/3rdparty/symfony/console/Application.php:901
September 04, 2019 14:22:32  Symfony\Component\Console\Application->doRunCommand() at /srv/nextcloud/www/3rdparty/symfony/console/Application.php:262
September 04, 2019 14:22:32  Symfony\Component\Console\Application->doRun() at /srv/nextcloud/www/3rdparty/symfony/console/Application.php:145
September 04, 2019 14:22:32  Symfony\Component\Console\Application->run() at /srv/nextcloud/www/lib/private/Console/Application.php:213
September 04, 2019 14:22:32  OC\Console\Application->run() at /srv/nextcloud/www/console.php:97
September 04, 2019 14:22:32  require_once() at /srv/nextcloud/www/occ:11
September 04, 2019 14:22:32
September 04, 2019 14:22:32 preview:pre-generate
September 04, 2019 14:22:32
```

Since it's a very large instance, I didn't let `preview:generate-all` run until the end but I assume both commands would work through the files in the same order, right?

**Comment by pousterlus** [comment]
Hello,

Same issue there.
Nextcloud 16.0.4
Preview Generator : 2.1.0

I tried to have some more informations but couldn't get more than @loelkes piece of log.

Thanks for having a look into it whenever possible :)

-- 
Leo.

**Comment by SpamReceiver** [comment]
I have the sme problem. Please help me solving it!

**Comment by pousterlus** [comment]
Hello SpamReceiver,

What filesystem are you using ?
If it's UFS, maybe that's related to this : https://github.com/nextcloud/server/pull/16747

-- 
Leo.

**Comment by SpamReceiver** [comment]
No, it's on a local ext4 mount. 
BTW, I have removed the folder "appdata_xxx/preview" and am now running a "preview:generate-all" on the server. I will report here success or failure after completion. Please hold on.

**Comment by pousterlus** [comment]
Yeah, OK.
And if it happens again, try to enter the folder, and create a new folder in it, and then report back the error here.

**Comment by SpamReceiver** [comment]
The preview generation via OCC is still running and does (so far) not report any issues.

But as I am impatient I opened the gallery in the browser and navigated ot a folder which previously had issues. In the nextcloud log I now find the following reports (occ log:watch):

`  Error    gallery            Exception: Preview generation has failed                                                                                                                                      2020-01-02T11:07:09+00:00

  Error    gallery            OCP\Files\NotFoundException:  at lib/private/Preview/Generator.php line 223                                                                                                   2020-01-02T11:07:09+00:00

                               0. lib/private/Preview/Generator.php line 126
                                  OC\Preview\Generator->getMaxPreview(OC\Files\SimpleFS\SimpleFolder {}, OC\Files\Node\File {}, "image\/jpeg", "")
                               1. lib/private/PreviewManager.php line 210
                                  OC\Preview\Generator->getPreview(OC\Files\Node\File {}, 2000, 2000, false, "fill", "image\/jpeg")
                               2. apps/gallery/lib/Service/PreviewService.php line 106
                                  OC\PreviewManager->getPreview(OC\Files\Node\File {}, 2000, 2000, false)
                               3. apps/gallery/lib/Controller/Preview.php line 167
                                  OCA\Gallery\Service\PreviewService->createPreview(OC\Files\Node\File {}, 2000, 2000, true, false)
                               4. apps/gallery/lib/Controller/Preview.php line 117
                                  OCA\Gallery\Controller\PreviewController->getPreviewData(OC\Files\Node\File {}, true, 2000, 2000, true, false)
                               5. apps/gallery/lib/Controller/PreviewController.php line 134
                                  OCA\Gallery\Controller\PreviewController->getData(1866294, 2000, 2000)
                               6. lib/private/AppFramework/Http/Dispatcher.php line 170
                                  OCA\Gallery\Controller\PreviewController->getPreview(1866294, 2000, 2000)
                               7. lib/private/AppFramework/Http/Dispatcher.php line 99
                                  OC\AppFramework\Http\Dispatcher->executeController(OCA\Gallery\Controller\PreviewController {}, "getPreview")
                               8. lib/private/AppFramework/App.php line 126
                                  OC\AppFramework\Http\Dispatcher->dispatch(OCA\Gallery\Controller\PreviewController {}, "getPreview")
                               9. lib/private/AppFramework/Routing/RouteActionHandler.php line 47
                                  OC\AppFramework\App::main(
                                    "PreviewController",
                                    "getPreview",
                                    OC\AppFramework\DependencyInjection\DIContainer {},
                                    {fileId:"1866294",_route:"gallery.preview.get_preview"}
                                  )
                              10. <<closure>>
                                  OC\AppFramework\Routing\RouteActionHandler->__invoke({fileId:"1866294",_route:"gallery.preview.get_preview"})
                              11. lib/private/Route/Router.php line 297
                                  call_user_func(OC\AppFramework\Routing\RouteActionHandler {}, {fileId:"1866294",_route:"gallery.preview.get_preview"})
                              12. lib/base.php line 997
                                  OC\Route\Router->match("\/apps\/gallery\/preview\/1866294")
                              13. index.php line 42
                                  OC::handleRequest(

                                  )
`
Indeed, there is no folder "appdata_xxx/preview/1866294".

`  Error    gallery            Exception: Preview generation has failed                                                                                                                                      2020-01-02T11:08:27+00:00

  Error    gallery            OCP\Files\NotFoundException:  at lib/private/Preview/Generator.php line 230                                                                                                   2020-01-02T11:08:27+00:00

                               0. lib/private/Preview/Generator.php line 126
                                  OC\Preview\Generator->getMaxPreview(OC\Files\SimpleFS\SimpleFolder {}, OC\Files\Node\File {}, "image\/jpeg", "")
                               1. lib/private/PreviewManager.php line 210
                                  OC\Preview\Generator->getPreview(OC\Files\Node\File {}, 200, 200, false, "fill", "image\/jpeg")
                               2. apps/gallery/lib/Service/PreviewService.php line 106
                                  OC\PreviewManager->getPreview(OC\Files\Node\File {}, 200, 200, false)
                               3. apps/gallery/lib/Controller/Preview.php line 167
                                  OCA\Gallery\Service\PreviewService->createPreview(OC\Files\Node\File {}, 200, 200, true, false)
                               4. apps/gallery/lib/Controller/Preview.php line 117
                                  OCA\Gallery\Controller\PreviewController->getPreviewData(OC\Files\Node\File {}, true, 200, 200, true, false)
                               5. apps/gallery/lib/Controller/PreviewController.php line 134
                                  OCA\Gallery\Controller\PreviewController->getData(247503, 200, 200)
                               6. lib/private/AppFramework/Http/Dispatcher.php line 170
                                  OCA\Gallery\Controller\PreviewController->getPreview(247503, 200, 200)
                               7. lib/private/AppFramework/Http/Dispatcher.php line 99
                                  OC\AppFramework\Http\Dispatcher->executeController(OCA\Gallery\Controller\PreviewController {}, "getPreview")
                               8. lib/private/AppFramework/App.php line 126
                                  OC\AppFramework\Http\Dispatcher->dispatch(OCA\Gallery\Controller\PreviewController {}, "getPreview")
                               9. lib/private/AppFramework/Routing/RouteActionHandler.php line 47
                                  OC\AppFramework\App::main(
                                    "PreviewController",
                                    "getPreview",
                                    OC\AppFramework\DependencyInjection\DIContainer {},
                                    {fileId:"247503",_route:"gallery.preview.get_preview"}
                                  )
                              10. <<closure>>
                                  OC\AppFramework\Routing\RouteActionHandler->__invoke({fileId:"247503",_route:"gallery.preview.get_preview"})
                              11. lib/private/Route/Router.php line 297
                                  call_user_func(OC\AppFramework\Routing\RouteActionHandler {}, {fileId:"247503",_route:"gallery.preview.get_preview"})
                              12. lib/base.php line 997
                                  OC\Route\Router->match("\/apps\/gallery\/preview\/247503")
                              13. index.php line 42
                                  OC::handleRequest(

                                  )
`
Indeed, folder "appdata_xxx/preview/247503" is empty.

**Comment by pousterlus** [comment]
What are the permissions/owner for appdata folder ?
And the "preview" folder too ?

**Comment by SpamReceiver** [comment]
They should be correct, IMO:
`drwxr-xr-x    15 www-data www-data      4096 Jan  2 11:48 appdata_octjtrbhomu0/`

`drwxr-xr-x 11403 www-data www-data 262144 Jan  2 14:04 preview/`

**Comment by pousterlus** [comment]
It seems to me that they are too, but on my instance, the perms also allows the group to write, not only the owner like in your case.
If I were you, I would give a try to set the "w" group perm on the two folders (775 instead of the actual 755). If the problem remains the same, set back the previous setting (755).

**Comment by pousterlus** [comment]
Hi,

Please follow-up :
Did you try to extend the write permission to the group ?
Did you manage to fix differently ?

Thanks for your feedback.

-- 
Léo.

**Comment by SpamReceiver** [comment]
Hi Léo! Thanks for asking.
I didn't change the permission settings, yet, as the script (`preview:pre-generate -vvv`) is still (!) running. Up to now, the "permission" error I have initially reported didn't re-appear. On the other side, I now have several pictures not showing up in the gallery or previews that keep the spinning wheel forever. So, I prefer to wait for the script having completed once and then check the status. Please stay tuned.

**Comment by pousterlus** [comment]
Aaah sorry, I didn't understand the process was still running :)
I hope it will be OK !

**Comment by SpamReceiver** [comment]
Well, unfortunately not. 

After running for really long, a few times interrupted by unreadable files, the script now came to a standstill. On a certain JPG file, I receive the "Could not create folder" exception and can't get over it.

Here is the output:
`
root@server:/# sudo -u www-data /usr/bin/php /mnt/data/var/www/nextcloud/occ preview:pre-generate -vvv > /mnt/data/var/log/preview-generate.log 2>&1
root@server:/# tail -1000f /mnt/data/var/log/preview-generate.log
2020-01-04T20:31:54+00:00 Generating previews for /XXX/files/AppData/Local/YYY/ZZZ.jpg
2020-01-04T20:31:54+00:00
2020-01-04T20:31:54+00:00 In Folder.php line 162:
2020-01-04T20:31:54+00:00
2020-01-04T20:31:54+00:00   [OCP\Files\NotPermittedException]
2020-01-04T20:31:54+00:00   Could not create folder
2020-01-04T20:31:54+00:00
2020-01-04T20:31:54+00:00
2020-01-04T20:31:54+00:00 Exception trace:
2020-01-04T20:31:54+00:00  () at /mnt/data/var/www/nextcloud/lib/private/Files/Node/Folder.php:162
2020-01-04T20:31:54+00:00  OC\Files\Node\Folder->newFolder() at /mnt/data/var/www/nextcloud/lib/private/Files/AppData/AppData.php:155
2020-01-04T20:31:54+00:00  OC\Files\AppData\AppData->newFolder() at /mnt/data/var/www/nextcloud/lib/private/Preview/Generator.php:432
2020-01-04T20:31:54+00:00  OC\Preview\Generator->getPreviewFolder() at /mnt/data/var/www/nextcloud/lib/private/Preview/Generator.php:118
2020-01-04T20:31:54+00:00  OC\Preview\Generator->getPreview() at /mnt/data/var/www/nextcloud/lib/private/PreviewManager.php:210
2020-01-04T20:31:54+00:00  OC\PreviewManager->getPreview() at /mnt/data/var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:205
2020-01-04T20:31:54+00:00  OCA\PreviewGenerator\Command\PreGenerate->processFile() at /mnt/data/var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:193
2020-01-04T20:31:54+00:00  OCA\PreviewGenerator\Command\PreGenerate->processRow() at /mnt/data/var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:164
2020-01-04T20:31:54+00:00  OCA\PreviewGenerator\Command\PreGenerate->startProcessing() at /mnt/data/var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:132
2020-01-04T20:31:54+00:00  OCA\PreviewGenerator\Command\PreGenerate->execute() at /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
2020-01-04T20:31:54+00:00  Symfony\Component\Console\Command\Command->run() at /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php:908
2020-01-04T20:31:54+00:00  Symfony\Component\Console\Application->doRunCommand() at /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php:269
2020-01-04T20:31:54+00:00  Symfony\Component\Console\Application->doRun() at /mnt/data/var/www/nextcloud/3rdparty/symfony/console/Application.php:145
2020-01-04T20:31:54+00:00  Symfony\Component\Console\Application->run() at /mnt/data/var/www/nextcloud/lib/private/Console/Application.php:213
2020-01-04T20:31:54+00:00  OC\Console\Application->run() at /mnt/data/var/www/nextcloud/console.php:97
2020-01-04T20:31:54+00:00  require_once() at /mnt/data/var/www/nextcloud/occ:11
2020-01-04T20:31:54+00:00
2020-01-04T20:31:54+00:00 preview:pre-generate
2020-01-04T20:31:54+00:00
`

**Comment by pousterlus** [comment]
Hey,

Can you access the preview folder and try to create one additionnal file (touch newfile.txt) and see what's the error message ?

-- 
Léo.

**Comment by SpamReceiver** [comment]
Good point:
`root@server:/mnt/data/var/nextcloud/data/appdata_octjtrbhomu0/preview# touch test
root@server:/mnt/data/var/nextcloud/data/appdata_octjtrbhomu0/preview# mkdir testdir
mkdir: cannot create directory ‘testdir’: Too many links
`

**Comment by pousterlus** [comment]
OK, so not a permission problem, but same old problem than many people have... but I thought it was for UFS filesystems only.
I suggest you to also tell about what you're experiencing in this thread : https://github.com/nextcloud/server/pull/16747

**Comment by kesselb** [comment]
https://serverfault.com/questions/827289/ubuntu-server-ext4-hitting-65000-subdirectory-limit

**Comment by pousterlus** [comment]
I'm not an expert in fs tuning... but it seems like a little bit scary to me :)
Hence I've got UFS and not ext4 I would'nt try it myself, but if you dare trying that solution, please report back here the result :)

-- 
Léo.

**Comment by SpamReceiver** [comment]
> https://serverfault.com/questions/827289/ubuntu-server-ext4-hitting-65000-subdirectory-limit

So, I did the check proposed in the link and it turned out that I don't have hashed directories:
`root@server:/# debugfs /dev/md126`
`debugfs 1.45.3 (14-Jul-2019)`
`htree /`
`debugfs:  htree /`
`htree: Not a hash-indexed directory`

However, I am not willing to change anything on the filesystem just for the previews of the Nextcloud Gallery. Instead, my position is that the preview implementation must be changed so that nobody faces this issue.

A change to the implementation can e.g. be to create sub-folders, each containing 1,000 or 32,000 or 64,000 previews.

**Comment by SpamReceiver** [comment]
After a quick lookup in the code I propose to change the following function:
server/lib/private/Files/AppData/AppData.php 
`	private function getPreviewFolder(File $file) {
		try {
			$folder = $this->appData->getFolder($file->getId());
		} catch (NotFoundException $e) {
			$folder = $this->appData->newFolder($file->getId());
		}
		return $folder;
	}
`

Instead of passing `$file->getId()`, something a bit more sophisticated should be passed, and the issue should be solved.

Of course, a migration script will be necessary, too.

**Comment by kesselb** [comment]
> I suggest you to also tell about what you're experiencing in this thread : [nextcloud/server#16747](https://github.com/nextcloud/server/pull/16747)

Have you looked at this pull request? Anyway this repository is the wrong place for this discussion. Previewgenerator is using the generation code from nextcloud/server. It's not possible to fix it here.

The proposal is accepted. It will probably done with a bigger refactoring of the preview code or before. 

cc @rullzer I'm not able to close a issue over here ;)

**Comment by SpamReceiver** [comment]
Now I have had a look at nextcloud/server#16747. It addresses the same issue, so I will be happy to have that fix.

**Comment by pousterlus** [comment]
> Have you looked at this pull request? Anyway this repository is the wrong place for this discussion. Previewgenerator is using the generation code from nextcloud/server. It's not possible to fix it here.

Give me a break with your contemptuous, haughty tone. The two threads seems to have the same consequences (impossible to generate previews due to filesystems subfolders limits), so refering it here doesn't seem such an mistake for other users looking for informations about it.

All developers aren't complete asses when it comes to talk with people and explain why they are mistaking instead of simply grumbling. Seems like you're not one of them.

-- 
Léo.

**Comment by kesselb** [comment]
Take a break :coffee: I suggested to have a look at the pull request (the one you mentioned earlier) because that's the right place to discuss about possible solutions.

I actually answered to `SpamReceiver` and it seems to me that he got it right. We don't have to discuss possible solutions a second time. Please try to read more carefully. The comment was not addressed to you.

**Comment by SpamReceiver** [comment]
Yes, I agree. As I understand the code, the app "PreviewGenerator" relies on the underlying server code for the actual preview generation. The app just triggers the generation for each file.

Thus, the management of the previews must be improved in a general manner, and nextcloud/server#16747 addresses this.

IMO, you may either close this issue now, or leave it open and mark it as "to be solved by nextcloud/server#16747". The latter has the advantage to potentially avoid new reports for this app.

**Comment by f4t-t0ny** [comment]
I had a similar issue with Nextcloud 22.2.4: 

```
2022-02-06T10:01:50+00:00 In Folder.php line 173:
2022-02-06T10:01:50+00:00                                         
2022-02-06T10:01:50+00:00   [OCP\Files\NotPermittedException]     
2022-02-06T10:01:50+00:00   Could not create folder: {$fullPath}  
2022-02-06T10:01:50+00:00                                         
2022-02-06T10:01:50+00:00 
2022-02-06T10:01:50+00:00 Exception trace:
2022-02-06T10:01:50+00:00   at /var/www/html/lib/private/Files/Node/Folder.php:173
2022-02-06T10:01:50+00:00  OC\Files\Node\Folder->newFolder() at /var/www/html/lib/private/Files/AppData/AppData.php:156
2022-02-06T10:01:50+00:00  OC\Files\AppData\AppData->newFolder() at /var/www/html/lib/private/Preview/Storage/Root.php:74
2022-02-06T10:01:50+00:00  OC\Preview\Storage\Root->newFolder() at /var/www/html/lib/private/Preview/Generator.php:472
2022-02-06T10:01:50+00:00  OC\Preview\Generator->getPreviewFolder() at /var/www/html/lib/private/Preview/Generator.php:132
2022-02-06T10:01:50+00:00  OC\Preview\Generator->generatePreviews() at /var/www/html/lib/private/PreviewManager.php:204
2022-02-06T10:01:50+00:00  OC\PreviewManager->generatePreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:243
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:214
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:212
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:183
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->generatePathPreviews() at /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php:131
2022-02-06T10:01:50+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /var/www/html/3rdparty/symfony/console/Command/Command.php:255
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/html/3rdparty/symfony/console/Application.php:1009
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/3rdparty/symfony/console/Application.php:273
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->doRun() at /var/www/html/3rdparty/symfony/console/Application.php:149
2022-02-06T10:01:50+00:00  Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:209
2022-02-06T10:01:50+00:00  OC\Console\Application->run() at /var/www/html/console.php:99
2022-02-06T10:01:50+00:00  require_once() at /var/www/html/occ:11
```

I added a log output in 
nextcloud/lib/private/Files/Node/Folder.php:173: 
`throw new NotPermittedException('Could not create folder, fullPath: '.$fullPath.', path: '.$path);`

After i checked and the folder did exist for me. So to fix this i added a check on the creation if the folder already exists to fix this and changed it to: 
`                        if (!$this->get($path) && !$this->view->mkdir($fullPath)) {
                                throw new NotPermittedException('Could not create folder, fullPath: '.$fullPath.', path: '.$path);
                        }
`

**Comment by phpusrpro** [comment]
https://preprocessor.space/questions/when-the-php-script-attempts-to-create-a-folder-it-encounters-an-error-preventing-it-from-successfully-creating
