### ISSUE TITLE
libpng error + silent failure

### ISSUE THREAD

**Issue by ukos-git** [nextcloud/previewgenerator#126]
I get an error while using `occ preview:generate-all`. The error is related to [this image](https://github.com/rullzer/previewgenerator/files/2334167/image.zip).
```
2018-08-29T23:53:09+00:00 Scanning folder /mak24gg/files/Pictures/arduino
libpng warning: iCCP: known incorrect sRGB profile
```
I was using imagemagick both, with `convert` and `mogrify` as suggestes [here](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile). The error message is now gone but the command still exits at the same directory but this time without saying anything.

I did not look into the code, but would it be possible to skip the command failure here by converting the image to a proper format before creating the preview?

**Comment by ukos-git** [comment]
This command fixes the `iCCP` error but also takes quiete long for a single file and is not standard `imagemagick`:

```
pngcrush -ow -rem allb -reduce file.png
```

```
   Total length of data found in critical chunks           =   1216179
   Critical chunk length, method   1 (ws 15 fm 0 zl 4 zs 0) =   2249696
   Critical chunk length, method   2 (ws 15 fm 1 zl 4 zs 0) =   1578885
   Critical chunk length, method   3 (ws 15 fm 5 zl 4 zs 1) =   1340735
   Critical chunk length, method   6 (ws 15 fm 5 zl 9 zs 0) =   1119137
   Critical chunk length, method   9 (ws 15 fm 5 zl 2 zs 2) >   1119137
   Critical chunk length, method  10 (ws 15 fm 5 zl 9 zs 1) =   1106821
pngcrush: iCCP: known incorrect sRGB profile
   Removed the cHRM chunk.
   Removed the sRGB chunk.
   Removed the iCCP chunk.
   Removed the pHYs chunk.
   Best pngcrush method        =  10 (ws 15 fm 5 zl 9 zs 1) =   1106821
     for output to pngout.png
     (8.99% critical chunk reduction)
     (no filesize change)

   CPU time decoding 5.236, encoding 19.970, other 0.008, total 25.214 sec.

```

**Comment by joshtrichards** [comment]
We can't really do much about the image itself here in this app (that would need to happen in the PNG/Image preview provider in Nextcloud Server itself), but we could at least skip if there's a failure.

Related: nextcloud/server#27290

**Comment by joshtrichards** [comment]
Let's track the silent stops on broken/unsupported/etc images in #142
