### ISSUE TITLE
Panorama photo casued preview generator to error

### ISSUE THREAD

**Issue by guy0nabuffalo** [nextcloud/previewgenerator#128]
Sorry if this issue has already been reported, I couldn't find one open already.
Panoramic photo taken with a Galaxy S9+ phone.
Nextcloud Version: 13.0.5.2
File Type: JPG
Size: 33.7MB

Cronjob stops completely when it hits this file. Ideally it would generate the preview, or skip it and continue generating previews.

Error | PHP | imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x44 at /var/www/nextcloud/lib/private/legacy/image.php#573
-- | -- | --

**Comment by grafixoner** [comment]
Same is happening to me.  I'm digging in today to see if I can wrap it in a try/catch to skip those problem files and isolate them.

**Comment by tfatrifork** [comment]
Experiencing the same issue here. It's quite a wide panorama so I guess that the issue is related to the aspect scaling calculations. 
I have attached the problematic panorama.
![p1030129-141panorama](https://user-images.githubusercontent.com/19605771/45378035-a9cd7300-b5fc-11e8-8b6a-fcdca828b2d0.JPG)

**Comment by joshtrichards** [comment]
> Ideally it would generate the preview, or skip it and continue generating previews.

Let's consolidate this into #142. 

Can't help with the jpeg processing itself (that provider isn't implemented here in this app - we just trigger the one registered within Nextcloud Server for the file type in question). If it's still occurring, that'll have to be dealt with in https://github.com/mextcloud/server
