### ISSUE TITLE
Preview data is 41% of data usage?

### ISSUE THREAD

**Issue by gmeks** [nextcloud/previewgenerator#129]
The preview data seems to a very high percentage? Is that normal? ( im using: ./occ preview:pre-generate )

 255.5 GiB [##########] /user0
  **186.0 GiB [#######   ] /appdata_oc7i1lu91hlw**
  141.1 GiB [#####     ] /user1
   43.5 GiB [#         ] /user2
   18.3 GiB [          ] /user3
    3.1 GiB [          ] /updater-oc7i1lu91hlw
  214.6 MiB [          ] user4
   35.2 MiB [          ]  nextcloud.log
    6.6 MiB [          ] /ncadmin
  260.0 KiB [          ] /files_external
  144.0 KiB [          ]  updater.log
   28.0 KiB [          ] /news
    4.0 KiB [          ]  .htaccess
    4.0 KiB [          ]  preview.log
    0.0   B [          ]  index.html
    0.0   B [          ]  .ocdata

Assuming this is normal, would it be a idea to have a maximum preview size? And perhaps remove old previews based on last access time ( Assuming linux has a last access information on files?)?

**Comment by Gatak** [comment]
Your first suggestions can already be done:
>  'enable_previews' => true,
>  'preview_max_x' => 1600,
>  'preview_max_y' => 1024,
>  'jpeg_quality' => 60,

You can also disable generation of some formats by selecting which ones to generate for:
>    'enabledPreviewProviders' =>
>  array (
>    0 => 'OC\\Preview\\PNG',
>  ),

Removing old, rarely used previews is a good idea. Expanding on that I think that the smaller <256px previews should remain to keep gallery and icons fast.

**Comment by danger89** [comment]
This should be documented better (especially the jpeg_quality).

**Comment by gmeks** [comment]
I followed the guide on 

> 
> 
> Your first suggestions can already be done:
> 
> > 'enable_previews' => true,
> > 'preview_max_x' => 1600,
> > 'preview_max_y' => 1024,
> > 'jpeg_quality' => 60,
> 
> You can also disable generation of some formats by selecting which ones to generate for:
> 
> > 'enabledPreviewProviders' =>
> > array (
> > 0 => 'OC\Preview\PNG',
> > ),
> 
> Removing old, rarely used previews is a good idea. Expanding on that I think that the smaller <256px previews should remain to keep gallery and icons fast.

My suggestion was more for a preview "pool size", not a size for pr preview image.

> 
> 
> This should be documented better (especially the 'jpeg_quality').
> And what about 'preview_max_filesize_image'?
> https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=config#previews
I used whatever was default at the time ( My was: sudo -u www-data php /var/www/nextcloud/occ preview:pre-generate )

I had to disable the plugin, as it was consuming way to much space, and generating to much IO.

**Comment by bcutter** [comment]
I have 3.000 media files with 9.1 GB in total - The preview Cache has 11.8 GB —> what the???

Is there a way to delete old thumbnails, some kind of cleanup task/command?

Or other idea: can I just delete the hole „.../.../appdata_ocXXXXX/preview“ folder and generate them from scratch afterwards? Or is there any additional job to be performed e. g. on the database?

**Comment by Gatak** [comment]
You can re-generate with the occ command. I have mounted a separate disk in the appdata/preview folder. Still, rather annoying. Especially since all previews take up valuable space in the sql database, making the whole installation slower. Preview metadata should be stored in its own table, perhaps even on Redis.

**Comment by ohthehugemanatee** [comment]
What metadata needs to be stored in the DB anyway? 

Surely all Nextcloud cares about is if a given preview format has been generated for a given file yet.  That's way faster to check with `file_exists()` than a DB lookup... particularly on Linux where it comes from the filesystem metadata cache. 

A common approach for this problem is to have a well-known path scheme, such as `appdata_ocXXXXX/previews/format_name/path/to/original/file.jpg` . Then a single fstat tells you everything you need to know, and clearing the preview cache is as easy as "rm -rf previews/" .

**Comment by Gatak** [comment]
This sounds like a much better approach. Is it technically doable?

I installed Lychee, a PHP photo gallery tool. The speed is instant, probably 10-100x faster than Nextcloud. This is on the same server and with the same photos.

**Comment by bcutter** [comment]
So what about files being deleted - are the previews generated for those automatically deleted too?

The whole huge space usage thing is a nasty one. I mean the full preview generation took me 26 hours generating 14300 files inside preview folder with a total size of 27 gigs... that´s pretty crazy. I´m starting to think of "What was the benefit of this preview generation, why should I use it?" :-(

**Comment by bcutter** [comment]
Update: at least the deletion of former previews (of deleted files - need to be completely deleted so also purged from trashbin) should work (https://github.com/rullzer/previewgenerator/issues/148).

**Comment by Djedouas** [comment]
I have observed a huge space taken by the previews as well: for my 100GB images I have a 100GB preview folder size!
I think it’s important to precise in the readme the huge size of the previews if no option on the image size is given...!
What are the recommended image size for the Nextcloud mobile app and webapp gallery?
Thanks

**Comment by Djedouas** [comment]
Here is a good doc with recommended sizes :)
https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/

**Comment by gmeks** [comment]
Thanks for that link.

**Comment by sbenve** [comment]
Is there a way to set these variables for nextcloud-snap?
` 
  'enable_previews' => true,
    'preview_max_x' => 1600,
    'preview_max_y' => 1024,
    'jpeg_quality' => 60,
`

I can edit the config.php file but it will be replaced on the next update.
Meanwhile, it does the job of limiting the max size of the preview images. So I want to make it stick.
Any chance of an app variable or config to do the same at the app level instead of the global config?

**Comment by st3iny** [comment]
The config file is probably replaced because you have some other `*.config.php` files in the config directory. They tend to overwrite the main settings.

I'm sorry but I have no experience with the snap package. You could try reaching out to its maintainers.

**Comment by Nebucatnetzer** [comment]
> Here is a good doc with recommended sizes :) https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/

This is a working version of the link: https://web.archive.org/web/20191023135735/https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/

**Comment by returntrip** [comment]
> I **do not** recommend using this app if you have enough processing power on your server and storage is limited. We implemented limiting parallel generation via mutexes in the core server some time ago so the old reasoning for using previewgenerator does not apply any longer (being that it might crash your server as there are too many parallel generation processes)

Perhaps this should be stated in the readme?

**Comment by st3iny** [comment]
Good point. I added a paragraph to the readme about the intended purpose from my point of view.
