### ISSUE TITLE
The current PHP memory limit is below the recommended value of 512MB.

### ISSUE THREAD

**Issue by kjlhgfds** [nextcloud/previewgenerator#131]
I found a way to make it work, but now I have the
`The current PHP memory limit is below the recommended value of 512MB.`
error in the log file.
I tried to set `memory_limit = 2G` in `.htaccess` and `.user.ini` in `/www` and in all the `php.ini` I could find, but it didn't work.
Does anyone has an idea ?

**Comment by oscarcarlsson** [comment]
Hi,

This is not an issue with this application, but a configuration issue with your setup in particular. As these issues are not intended for support requests (but issues with the application code etc) this issue will probably never get any real attention here, and the author will/should close this.

In my setup (which is different from yours, I use nginx and php-fpm, while I'm guessing you are using Apache and mod_php), I had two different configuration files for running it with my webserver (php-fpm in my case) and one configuration for running it from cron (pretty much like running it from the command line). I had to setup the cli (command line interface) php configuration separately from my php-fpm, and increased my memory limit to 512M for both of these.

I hope this helps you in some way.
