### ISSUE TITLE
Feature Request - add more images file types 

### ISSUE THREAD

**Issue by jsavalle** [nextcloud/previewgenerator#133]
Could it be considered to add preview for *.eps *.ai *.psd ?

Storing on the cloud design files which are not pure images aren't rendered in the gallery view which is sad.

**Comment by joshtrichards** [comment]
Preview format support is provided by apps specific to those formats and/or built into Nextcloud Server. The `previewgenerator` app itself does not provide any of the functionality related to specific file formats. It merely handles offline triggering of already functioning preview generators within Nextcloud Server.

**Comment by st3iny** [comment]
Additionally to what Josh said, requests for new formats always have to be addressed at the [server repository](https://github.com/nextcloud/server/).
