### ISSUE TITLE
excluding external storage folder.

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/previewgenerator#151]
Hi.

using Scalways S3 as an external storage for my 15.0.4 server, i notice my server reaction as slowing.

Notice preview generator has started to scan and preview the external storage. 

How to avoid it ?
It is slow, useless as s3 is a redundant backup for me and don't need to be scan

sound stupid, can't remember or find the equivalent of .nomedia

**Comment by filthycoding** [comment]
I agree.

**Comment by koying** [comment]
Running  NC16, there is "Enable preview" setting on the external storages.
Unfortunately, it looks like the generator ignores it

**Comment by hashworks** [comment]
Any plans on this? The "enable preview" setting seems like the right way to exclude them.

**Comment by hashworks** [comment]
I guess we have to do the following:

Load all mounts:
```php
use OCA\Files_External\Service\GlobalStoragesService;

// [...]

	/**
	 * @var GlobalStoragesService
	 */
	protected $globalService;

	public function __construct(GlobalStoragesService $globalService) {
		parent::__construct();
		$this->globalService = $globalService;
	}

// [...]

$mounts = $this->globalService->getStorageForAllUsers();
```

Then for every mount check the mount path and the preview setting in the options:
```php
$mountPath = $mount->getMountPoint(); ; // String
$mountOptions = $mount->getMountOptions(); // $key => $value
```

**Comment by hashworks** [comment]
Until a new version is released (with the above pull request) a workaround is to create a `.nomedia` file in the external mount.
