### ISSUE TITLE
Pregenerated thumbnails are slow to load

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/previewgenerator#153]
I have the problem, that even though I managed to create previews for all my files using `occ preview:generate-all` the displaying of these images is dramatically slow. In the following image you see the timing of opening a folder in NC with a single image inside:
![load](https://user-images.githubusercontent.com/8202922/53495640-9c1f8300-3aa0-11e9-9d29-97cd1886b3f6.png)
Waiting is roughly 500ms (seems long to me but not the worst) but receiving is 5s! This means I only could transmit ~2kB/s. The line to the machine should be capable of doing much more. 
To investigate further I looked into different potential problems and bottlenecks.

- The network is idle mostly during the test. The line is capable of >2MB/s. I can start uploads in the background causing almost no effect, so that I assume it is not related to pure bandwidth.
- The files have a pre-generated preview available. This is used. I checked by changing the thumbnails (making them much darker) to see if these are found and used.
- The machine has plenty of RAM ready to use. At the moment there are almost 25GB used as buffers/os cache, thus free.
- The hard disk can access the files quickly. Copying/reading the files on the machine locally works in the blink of an eye. Reading from the file system should not take this long to account for the 5 sec.
- The CPU spikes up during the transfer of the image. When I open the image (especially the full screen version), the CPU usage increases quite for some time with the `php` processes causing the load. I would assume that the page does not have to do much except for checking the session, looking up the path of the thumbnail and delivering the thumbnail. This should not take too much effort, however it is delayed quite much.

Not all requests take exactly the same scheme. Other folders are not that extreme as the example file. I think there goes on something behind the scenes that I do not get. Can anyone tell me, what I can try further to track down th issue right now? (I honestly do not know if this is a problem of the preview app, the core, or my installation.)

**Comment by ohthehugemanatee** [comment]
This is more likely to be in Nextcloud itself than previewGenerator.  Looks like preview images are stored in the appData directory, outside of the webroot. The web server can't serve them directly, they have to be streamed from PHP. This also makes sense for permission checks - you don't want the wrong user having access to preview versions of your images.

**Comment by cClaude** [comment]
@christianlupus According to @ohthehugemanatee  comment, this issue should be closed. You can open an issue in nextcloud server project optimizations in last versions are not enough for you.

**Comment by christianlupus** [comment]
I will close it here as it is quite dated and I have updated the whole system since.
