### ISSUE TITLE
please ignore .@_thumb folders

### ISSUE THREAD

**Issue by ghost** [nextcloud/previewgenerator#159]
please ignore .@_thumb folders.

the command: ./occ preview:generate-all -vvv
generate preview pictures from the windows preview pictures (.@thumb)...
my nextcloud server is very slooooowly therefore

can you fix it?

**Comment by cClaude** [comment]
This request is very similar to https://github.com/rullzer/previewgenerator/issues/157

@ghost Could you put your comment on https://github.com/rullzer/previewgenerator/issues/157 and clone this issue ?

**Comment by joshtrichards** [comment]
Duplicate of #157
