### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by jsanfe** [nextcloud/previewgenerator#161]
Hi all!
I downloaded and install preview generator, but im unable to start the system. 
Im runninng nextcloud via freenas server into a jail, and i have to separated shells. 
I writte the command: ./occ preview-pregenerate:all and systems says Command not found.

any idea? 
Thanks!

**Comment by jkingcis** [comment]
Hi @jsanfe 
This command should be executed as the web server user (www-data on Debian/Ubuntu or apache for Red Hat/CentOS). Try this command:
# which php --> Write down your PHP binary path (usually /bin/php). If you0re using a different PHP version than your OS provides, just use it.
# /bin/sudo -u <webserver_user> /path/to/php /path/to/occ preview:generate-all 

Just an example:
# /bin/sudo -u apache /bin/php /var/www/html/yoursite/occ preview:generate-all -vv

The -vv means verbose. Hope this helps

**Comment by zhouqiancheng** [comment]
I have met the same issue.

To solve it I install PHP, and But still got some other issue.
In my case, I use SNAP to install nextclode. Anything else should I do?

Here is my cmd and issue:
```
root@luke-desktop:/snap/nextcloud/21026/htdocs# sudo -u www-data php /snap/nextcloud/21026/htdocs/occ preview:generate-all
App directory "/snap//current/htdocs/apps" not found! Please put the Nextcloud apps folder in the Nextcloud folder or the folder
```

Please kindly help me.

Regards,
Luke

**Comment by joshtrichards** [comment]
Hi. Thanks for the report and I'm sorry you all ran into this issue! However this is definitely a support request about your environment and not a bug in `previewgenerator` nor Nextcloud.

This venue is for bug reports and enhancement requests for the core developers.

This query is perfect topic to bring up at the [community help forum](https://help.nextcloud.com). In fact, if you search there you'll find others that have had the same issue when trying to use `occ` at the command line and how they solved it. :-)

This Issue should be closed out.
