### ISSUE TITLE
tmp files can fill up file system

### ISSUE THREAD

**Issue by jgloss** [nextcloud/previewgenerator#164]
The temp files created in /tmp can accumulate if the preview generator crashes and needs to be restarted. The program should remove old temp files when called to prevent filling up the file system. This is probably only noticeable for large uncompressed tiffs, but it has happened for me several times. Deleting /tmp/oc*  and /tmp/magic* before re-running the preview generator prevents filling up the file system. The program should do this automatically when started.

Edit: I believe the problem may be caused by nextcloud automatically creating previews at the same time. I don't think it used to automatically do that. If you stop the apache service and then use the preview generator app, all goes fine. Can someone close or delete this issue?

**Comment by cClaude** [comment]
@jgloss You probably could close this issue by yourself... So please close it to avoid noise...

**Comment by jgloss** [comment]
no
