### ISSUE TITLE
Previews not working -  Data is not in a recognized format or Image is not a JPEG"

### ISSUE THREAD

**Issue by kevo-gt** [nextcloud/previewgenerator#165]
I have the following setup:

Nextcloud 16.0
PreviewGenerator: 2.1.0
PHP Version => 7.3.5 

When I run the "php ./occ  preview:generate-all -vvv" command, the images don't display on Nextcloud and message in the log files is either:

`""GET","url":"\/index.php\/core\/preview?fileId=208&c=6bcc89e7da485ae2355f97f629e4aabf&x=500&y=500&forceIcon=0","message":"OC_Image->fixOrientation() Image is not a JPEG.""`

OR

`"PHP","method":"GET","url":"\/index.php\/core\/preview?fileId=259&c=5ed0d049c882745369f1d66d3fe169bb&x=500&y=500&forceIcon=0","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/nextcloud\/lib\/private\/legacy\/image.php#622"`

I got the same message on when generating the images on a platform which had PHP 7.2.

Any advice on what I need to do to get the generated images to generate and load correctly?

Thanks

**Comment by james-cook** [comment]
Try updating libgd - my impression is that 2.2.5 gives the correct error so that preview generation can continue for images that are not incorrect. 
I had a similar issue: https://github.com/matiasdelellis/facerecognition/issues/149#issuecomment-501259539_

**Comment by kevo-gt** [comment]
thanks but it still did not work. I upgraded to libgd-2.2.5_1,1 and re-run the generator but same error shows up in the log files

**Comment by joshtrichards** [comment]
If you want to figure out which file is triggering the issue you can edit this line:

https://github.com/nextcloud/server/blob/a17d01951fdf72a37036fe67cba4009b03b5723e/lib/private/legacy/OC_Image.php#L436

(aka: /lib/private/legacy/OC_Image.php)

To:

```
            $this->logger->debug('OC_Image->fixOrientation() Image is not a JPEG: ' . $this->filePath, ['app' => 'core']);
```

**Comment by joshtrichards** [comment]
If this is still occurring in more recent versions of Nextcloud Server, please create an issue with your environment's details (and ideally an example image if possible) in the `server` repo (which is where these image preview providers are located): https://github.com/nextcloud/server
