### ISSUE TITLE
adding gpu accerelation

### ISSUE THREAD

**Issue by Milokita** [nextcloud/previewgenerator#173]
according to https://imagemagick.org/script/opencl.php, resize tasks can be offload to GPU

**Comment by TheOneWithTheBraid** [comment]
@rullzer Is this already implemented or are there any plans to do this?

**Comment by ronny332** [comment]
you need a php binding for imagemagick, previewgenerator can't do it on its own.

**Comment by cClaude** [comment]
@Milokita According to @ronny332 answer, I think ti issue should be **close** (or perhaps rename this issue with something like: **Why using GPU acceleration is not an option**)
