### ISSUE TITLE
nextcloud app Preview Generator remains disabled

### ISSUE THREAD

**Issue by muligamma** [nextcloud/previewgenerator#177]
APP Preview Generator, return disables after enabling it. because?

version Necxtcloud 17

Thank you

**Comment by madbrain-** [comment]
Same here, nothing regarding this in the nextcloud.log. Removed the App and reinstalled - same Problem. Can I look for other logs somewhere?

**Comment by joshtrichards** [comment]
This is an old issue so hopefully you've found a solution elsewhere. If not, let us know. :-)

Closing out due to age for now.
