### ISSUE TITLE
Does previewgenerator support movie files

### ISSUE THREAD

**Issue by per2jensen** [nextcloud/previewgenerator#196]
I am in doubt if the previewgenerator supports generating previews for movie files.

The documentation does not mention movieclips, nor is there any hint of possible requirements or config settings.

I have built a snap with the following content:
- /usr/bin/ffmpeg
- config.php:
```

  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\Image',
    2 => 'OC\\Preview\\Movie',
    3 => 'OC\\Preview\\MP4',
    4 => 'OC\\Preview\\MKV',
    5 => 'OC\\Preview\\AVI',
  ),
```

I have run the command:
   `sudo nextcloud.occ preview:generate-all -vvv`
without errors. New photos do get previews built, but an .mp4 file  does not.

Is there something I have missed ?

Regards,
Per

**Comment by joshtrichards** [comment]
Snap specific matter: https://github.com/nextcloud-snap/nextcloud-snap/issues/1327#issuecomment-1629670568

Nothing for us to do here about it.
