### ISSUE TITLE
How do I regenerate on already generated previews?

### ISSUE THREAD

**Issue by rjberm** [nextcloud/previewgenerator#217]
I have changed the sizes of previews on settings but would like re-generate all the previews again.
the following command only does new ones and looks like its skipping already generated previews

sudo -u www-data php ./occ preview:generate-all -vvv

**Comment by rarealphacat** [comment]
try delete the folder and regenerate?

**Comment by hajo62** [comment]
Would like to know same. Does removing the folder do all needed? No etries in the database?

**Comment by Sim0nW0lf** [comment]
Try [this](https://help.nextcloud.com/t/remove-preview-files-without-occ-and-without-posix/31634).
That might work.
For me that wasn't enough but only because I migrated the db from another instance. I dropped the whole oc_preview (don't remember the name) table and recreated it.

**Comment by st3iny** [comment]
**WARNING:** Proceed at your own risk. *Always* create backups before issuing such disruptive commands.

There is no official way to accomplish this. However, you could manually delete the preview folder (e.g. `rm -r /var/www/nextcloud/data/appdata_ocvmms8559yd/preview`) and then run `occ files:scan-app-data`.
