### ISSUE TITLE
An unhandled exception has been thrown: TypeError: Argument 1

### ISSUE THREAD

**Issue by motoride** [nextcloud/previewgenerator#222]
Preview generator works as expected for all files in external storage except .mov. I have ffmpeg

An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\PreviewGenerator\Command\Generate::parseFolder() must implement interface OCP\Files\Folder, instance of OC\Files\Node\File given, called in /.../public_html/apps/previewgenerator/lib/Command/Generate.php on line 147 and defined in /.../public_html/apps/previewgenerator/lib/Command/Generate.php:158
Stack trace:
#0 /.../public_html/apps/previewgenerator/lib/Command/Generate.php(147): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\File))
#1 /.../public_html/apps/previewgenerator/lib/Command/Generate.php(117): OCA\PreviewGenerator\Command\Generate->generatePathPreviews(Object(OC\User\User), '/...')
#2 /.../public_html/apps/mail/vendor/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /.../public_html/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /.../public_html/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /.../public_html/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /.../public_html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /.../public_html/console.php(100): OC\Console\Application->run()
#8 /.../public_html/occ(11): require_once('/home/...')
#9 {main}[... public_html]$

Any ideas ?

**Comment by bgbearcatfan** [comment]
I'm getting the exact same error with .MP4 files.  Did you find a fix for this?

**Comment by st3iny** [comment]
Does anyone still encounter this error?

**Comment by motoride** [comment]
I've seen your reply, but I'm having a separate issue with ffmpeg at the moment on my server. Once I get it resolved (ETA about 7 days) I will try and test again.

**Comment by st3iny** [comment]
I'll close this issue as there hasn't been a response. Feel free to reopen this one or open a new one if the error still occurs.
