### ISSUE TITLE
Doesn't work with .heic

### ISSUE THREAD

**Issue by avinfo79** [nextcloud/previewgenerator#230]
After all pictures were generated I found that .heic files still doesn't have a preview in mobile app and desktop. After click on it preview generated. So, assume that, I think for .heic it perhaps must do some extra work or different parameters to generate preview. I can help with this if needed, just let me know what you need to fix it.

**Comment by shelterx** [comment]
I don't think it's an an issue with preview generator, you need ImageMagick with heic support on your system.

**Comment by Ergerbolt** [comment]
Hi,

what is the standard path to config.php on a pi4 with normal installation?

**Comment by st3iny** [comment]
@Ergerbolt The default path on Debian based systemd should be `/var/www/html/config/config.php` but it depends.

Closing because of what @shelterx said.
