### ISSUE TITLE
Delete all previews

### ISSUE THREAD

**Issue by denics** [nextcloud/previewgenerator#231]
Dear all, is it possible to delete all the previews generated? I have installed the module and generated the previews. Everything went fine, but NC now goes "out of memory" because I forgot to exclude few thousands of working images. I uninstalled the module, but I see that it left the table in the db and I do not know how to remove the items from oc_filecache:
|  68931 |       2 | appdata_oc3d3rrro68n/preview/a/1/5/f/9/8/9/14318

**Comment by shelterx** [comment]
You need to delete the previews generated from the appdata_[generatedstring]/preview directory if you haven't done that.

Then to remove deleted previews from db run:
`occ files:scan-app-data `

**Comment by deathblade666** [comment]
FWIW I have done this and it still seems to hold on to the generated previews somehow.. I'm not usre but maybe it's cause I'm using an external drive mouted via SMB? but as it stand I can not open nearly any image or video files and i get a distorted preview image.

**Comment by st3iny** [comment]
**WARNING:** Proceed at your own risk. There is no official way to accomplish this. *Always* create backups before issuing such disruptive commands.

You could try following https://github.com/nextcloud/previewgenerator/issues/217#issuecomment-970223826.
