### ISSUE TITLE
Previews are distorted - Cant open images

### ISSUE THREAD

**Issue by deathblade666** [nextcloud/previewgenerator#232]
I am running the latest stable release of NC. I installed Preview-Generator and ran ./occ preview:generate-all and now my thumbnails are distorted and I can not open my image files within NC. I have run ./occ preview:delete_old nothing, I have deleted the data/data_app/preview folder and it's contents and ran ./occ files:scan-app-data. Nothing. I have removed the app and rebooted the server after everything and still my thumbnails are distorted and I can not open image files.

The files are being stored on an external drive I have connected to my NC server through smb. I do not know if that has anything to do with it or not.

Aslo I have looked and have found no logs for this issue.. I am open to any suggestions.

**Comment by st3iny** [comment]
Good idea. However, support for imaginary was added fairly recently so I think something else is wrong here.

**Comment by deathblade666** [comment]
Closing cause stale and the issue hasn't reoccurred since. Best guess is it was fixed in an update
