### ISSUE TITLE
imagecreatetruecolor(): Argument #1 ($width) must be greater than 0 causes generate-all to fail

### ISSUE THREAD

**Issue by ACiDGRiM** [nextcloud/previewgenerator#252]
I have a lot of installer folders that contain image resources. frequently there are some images that are malformed, either intentionally or for other reasons. This causes the generate-all command to fail when it encounters this error.

Ideally the error would be thrown, but continue to process other images.

An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #1 ($width) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:933
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(933): imagecreatetruecolor(0, 64)
#1 /var/www/html/lib/private/legacy/OC_Image.php(905): OC_Image->preciseResizeNew(0, 64)
#2 /var/www/html/lib/private/legacy/OC_Image.php(1155): OC_Image->resizeNew(64)
#3 /var/www/html/lib/private/Preview/Generator.php(430): OC_Image->resizeCopy(64)
#4 /var/www/html/lib/private/Preview/Generator.php(186): OC\Preview\Generator->generatePreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OCP\Image), 0, 64, false, 1, 400, '')
#5 /var/www/html/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'image/png')
#6 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(203): OC\PreviewManager->generatePreviews(Object(OC\Files\Node\File), Array)
#7 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(174): OCA\PreviewGenerator\Command\Generate->parseFile(Object(OC\Files\Node\File))
#8 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#9 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#10 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#11 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#12 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#13 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#14 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#15 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(155): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#16 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(123): OCA\PreviewGenerator\Command\Generate->generateUserPreviews(Object(OC\User\User))
#17 /var/www/html/lib/private/User/Manager.php(646): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}(Object(OC\User\User))
#18 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(124): OC\User\Manager->callForSeenUsers(Object(Closure))
#19 /var/www/html/custom_apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/custom_apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/custom_apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/custom_apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/console.php(99): OC\Console\Application->run()
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')

**Comment by Germwalker** [comment]
same error on nextcloud 22.1.1, even after a preview:repair the command preview:generate-all throw this trace : 

`ValueError: imagecreatetruecolor(): Argument #1 ($width) must be greater than 0 in /var/www/nextcloud/lib/private/legacy/OC_Image.php:933
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/OC_Image.php(933): imagecreatetruecolor()
#1 /var/www/nextcloud/lib/private/legacy/OC_Image.php(905): OC_Image->preciseResizeNew()
#2 /var/www/nextcloud/lib/private/legacy/OC_Image.php(1155): OC_Image->resizeNew()
#3 /var/www/nextcloud/lib/private/Preview/Generator.php(430): OC_Image->resizeCopy()
#4 /var/www/nextcloud/lib/private/Preview/Generator.php(186): OC\Preview\Generator->generatePreview()
#5 /var/www/nextcloud/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews()
#6 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(203): OC\PreviewManager->generatePreviews()
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(174): OCA\PreviewGenerator\Command\Generate->parseFile()
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#15 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(155): OCA\PreviewGenerator\Command\Generate->parseFolder()
#16 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(123): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#17 /var/www/nextcloud/lib/private/User/Manager.php(646): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#18 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(124): OC\User\Manager->callForSeenUsers()
#19 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#23 /var/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#24 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#25 /var/www/nextcloud/occ(11): require_once('...')
#26 {main}`

**Comment by Germwalker** [comment]
This quick & dirty fix allow the generate-all to continue if the image is broken : 

`nano +933 /var/www/nextcloud/lib/private/legacy/OC_Image.php`

replace `$process = imagecreatetruecolor($width, $height);` with this block : 

`                if ($width > 0 and $height > 0){
                        $process = imagecreatetruecolor($width, $height);
                } else {
                        $process = false;
                }`

**Comment by yatli** [comment]
I'd like to try @Germwalker 's workaround but I'm with a snap installation and the file appears to be readonly :(
Do I need to wait for the next release?

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/server/pull/29632.

**Comment by mryshakow** [comment]
i read a few times that this issue should be fixed... but i still have this issue on Nextcloud 23.0.0. What am I missing? 

`An unhandled exception has been thrown:
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/html/lib/private/legacy/OC_Image.php:780
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(780): imagecreatetruecolor(2544, 4294963796)
#1 /var/www/html/lib/private/legacy/OC_Image.php(616): OC_Image->imagecreatefrombmp('/tmp/oc_tmp_z1v...')
#2 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->loadFromFile('/tmp/oc_tmp_z1v...')
#3 /var/www/html/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\Image->getThumbnail(Object(OC\Files\Node\File), 4096, 4096)
#4 /var/www/html/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\BMP), Object(OC\Files\Node\File), 4096, 4096)
#5 /var/www/html/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/bmp', '')
#6 /var/www/html/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'image/bmp')
#7 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(243): OC\PreviewManager->generatePreviews(Object(OC\Files\Node\File), Array)
#8 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#10 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#11 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#12 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#13 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#14 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#15 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#16 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->generateUserPreviews(Object(OC\User\User))
#17 /var/www/html/lib/private/User/Manager.php(657): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}(Object(OC\User\User))
#18 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(139): OC\User\Manager->callForSeenUsers(Object(Closure))
#19 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/console.php(99): OC\Console\Application->run()
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main}command terminated with exit code 1
`
