### ISSUE TITLE
PHP Fatal error:  gd-webp cannot allocate temporary buffer in /var/www/html/lib/private/legacy/OC_Image.php on line 620

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/previewgenerator#256]
`preview:generate-all` and `preview:generate` both crash with this error:

```
PHP Fatal error:  gd-webp cannot allocate temporary buffer in /var/www/html/lib/private/legacy/OC_Image.php on line 620
```

I assumed it was some kind of webp parsing bug, but it happens when it is trying to generate previews for a directory with GIF files.

**Comment by meonkeys** [comment]
Aha! The issue was a file with `RIFF (little-endian) data, Web/P image` data, but the filename ended in `.gif`. Fixed by renaming it from `example.gif` to `example.webp`.

**Comment by heinhuiz** [comment]
I'm getting this same error sometimes (on line 751), maybe once per day after (during) a preview:pre-generate cron job. The script is called every 10 minutes, meaning that the error occurs roughly once every 150 runs.
