### ISSUE TITLE
gencache_init: Failed to create directory: /var/www/.cache/samba - Permission denied

### ISSUE THREAD

**Issue by SpamReceiver** [nextcloud/previewgenerator#264]
I have the folowing cron job for the user www-data:   
``0     2  *  *  *  /usr/bin/php /mnt/data/var/www/nextcloud/occ preview:pre-generate -vvv > /mnt/data/var/log/preview-generate.log 2>&1``

When I check the log, I find many of the following error messages:   
``gencache_init: Failed to create directory: /var/www/.cache/samba - Permission denied``

User www-data has no access to ``/var/www``. My web root folder is ``/mnt/data/var/www``.

Happens with Nextcloud 22 + Preview Generator 3.x (now on 3.30, but happened also earlier).

**Comment by st3iny** [comment]
This is a very old and known issue of smbclient. It can be fixed by applying the following workaround: Create the folder /var/www/.cache/samba manually and grant your web server user (e.g. www-data) access to it.

**Comment by SpamReceiver** [comment]
What will be the impact of not fixing the issue? Will no previews be generated?
