### ISSUE TITLE
occ config does not working

### ISSUE THREAD

**Issue by horphi0815** [nextcloud/previewgenerator#267]
Nextcloud 23.0.0.

root@e5fe1d8732ce:/# occ config:app:set --value="32 64 1024"  previewgenerator squareSizes
Too many arguments, expected arguments "command" "app" "name". 
config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>

only accept, but result is empty
root@e5fe1d8732ce:/# occ config:app:set --value="32,64"  previewgenerator squareSizes
Config value squareSizes for app previewgenerator set to 32,64

root@e5fe1d8732ce:/# occ config:app:get previewgenerator squareSizes
root@e5fe1d8732ce:/#

**Comment by st3iny** [comment]
It's `previewgenerator` instead of `preview` in the get command.

Please run `occ config:app:get previewgenerator squareSizes`.

**Comment by horphi0815** [comment]
Thx for this hint,  but this does not solve the problem...
root@e5fe1d8732ce:/# occ config:app:get previewgenerator squareSizes
32,64

i would like to configure previewgenerator, to only compute the prefered solutions
![grafik](https://user-images.githubusercontent.com/39962016/145050424-6c090a6d-f927-48c1-b2ce-aad523a88bf1.png)

**Comment by horphi0815** [comment]
@st3iny some news regarding this issue?

BR

**Comment by florie1706** [comment]
+1

**Comment by st3iny** [comment]
Keep in mind, that this setting **only** affects previews which are (pre-)generated by the app. If a generation is triggered by any other source, this setting will be ignored. E.g. a larger preview will be generated upon viewing the file in the files app.

Please refer to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#previews for more information about configuring previews globally.

**Comment by st3iny** [comment]
**PS:** I just looked at the code and realized that the sizes have to be separated by a space.

E.g. `occ config:app:set --value="32 64"  previewgenerator squareSizes`

**Comment by horphi0815** [comment]
But if i set the values separated by space, the  error appears
Too many arguments, expected arguments "command" "app" "name".
config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] 

the resolution of the parameters result to the issue

**Comment by horphi0815** [comment]
root@7275c2e8b0f7:/# occ config:app:set **--value='32 64 1024**'  previewgenerator squareSizes
Too many arguments, expected arguments "command" "app" "name".                                                    
config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>

root@7275c2e8b0f7:/# occ config:app:set **--value='32,64,1024'**  previewgenerator squareSizes
Config value squareSizes for app previewgenerator set to 32,64,1024

**Comment by st3iny** [comment]
This could be a problem with the quoting of the argument. I'll give this a try later.

**Comment by Rakhmanov** [comment]
Related https://github.com/linuxserver/docker-nextcloud/issues/179.
Solved by escaping quotes. Like : `occ config:app:set --value=\"
32 64\" previewgenerator squareSizes`
