### ISSUE TITLE
Deleting Previews

### ISSUE THREAD

**Issue by Andrei1744** [nextcloud/previewgenerator#268]
Hi. How can I delete the previews from this app? I'm using Truenas. Any help is appreciated!

**Comment by st3iny** [comment]
Please use the search feature next time. Questions like this have been asked multiple times already.

**WARNING:** Proceed at your own risk. There is no official way to accomplish this. *Always* create backups before issuing such disruptive commands.

You could try following https://github.com/nextcloud/previewgenerator/issues/217#issuecomment-970223826.

**Comment by Andrei1744** [comment]
> Please use the search feature next time. Questions like this have been asked multiple times already.
> 
> **WARNING:** Proceed at your own risk. There is no official way to accomplish this. _Always_ create backups before issuing such disruptive commands.
> 
> You could try following [#217 (comment)](https://github.com/nextcloud/previewgenerator/issues/217#issuecomment-970223826).

Problem is that I don't have that folder structure. I only have /usr/local/var and in var I have just to folders, db and lib

**Comment by st3iny** [comment]
This bug tracker is meant only for bugs but let me try to help.

First of all, which OS and web server are you running? Some operating systems have their apache data in `/srv/http/`. So your nextcloud previews could also be in `/srv/http/data/appdata_XXX/preview`.

Do you have a custom data path? Search your `config.php` for `'datadirectory' => '...'`.

**Comment by msberends** [comment]
> Please use the search feature next time. Questions like this have been asked multiple times already.

Then put it in README if so many people are looking for an answer. The issue tracker of GitHub isn't really suitable for searching answers to questions. 

I've been looking across multiple forums now for this issue. Still not sure after removing the `appdata_*/preview` folder where the log is (apparently not in the `oc_preview_generation` database table), since `occ preview:generate-all` now ignores files that have no preview anymore.

**Comment by st3iny** [comment]
> Then put it in README if so many people are looking for an answer. The issue tracker of GitHub isn't really suitable for searching answers to questions.

I agree but I'm hesitant to add the deletion of previews to the FAQ because it's not supported. However, If so many of you report that it works just fine I might reconsider adding it to the FAQ.

**Comment by st3iny** [comment]
I added a section to the FAQ.
