### ISSUE TITLE
Config Location of previewgenerator (and other apps)

### ISSUE THREAD

**Issue by Leviathan09** [nextcloud/previewgenerator#270]
I dont' know where to ask and couldn't find anything with google yet

I wonder where the app settings are stored.
for example:
When i enter the command -> `./occ config:app:set --value="32 64 1024"  previewgenerator squareSizes` in which file/location is this setting saved?
Is there a special config file? Because it's not in the config.php of my nextcloud and also not in the SizeHelper.php of the app

But in the SizeHelper.php there are some lines:
`$getCustomSizes = function (IConfig $config, $key) {`
`$TXT = $config->getAppValue('previewgenerator', $key, '');`
`$values = [];`
`if ($TXT !== '') `

So i think there must be a config file or so where all the information is stored

Maybe someone can help me with this
Thanks

**Comment by st3iny** [comment]
App config is saved in your database. Have a look at the `oc_appconfig` table. In there you can find the configuration values of all your apps.

**Comment by Leviathan09** [comment]
> App config is saved in your database. Have a look at the `oc_appconfig` table. In there you can find the configuration values of all your apps.

Thank you @st3iny
