### ISSUE TITLE
Preview Generator throws error at Office Documents

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/previewgenerator#275]
In Use: Ubuntu 20.04
Nextcloud Server: 22.2.3 
Libreoffice
PHP: 8.0.13
Preview Generator: 3.4.1

Error Message:
javaldx failed!

Warning: failed to read path from javaldx

Error: source file could not be loaded

2021-12-20T11:13:02+00:00 Generating previews for /user/AnonymPathToFile/WV test.doc

/tmp/owncloud-oc6d8c5lzdz7//user/config/javasettingsLinuxX86_64.xml:5: parser error : Extra content at the end of the document

xsi:nil="true"></enabled>

**Comment by st3iny** [comment]
Thanks for the report. 

Could you share the test document so that I can debug this issue? I can share an email address if you don't want to attach it publicly.

**Comment by MrLoverLoverMMMM** [comment]
For example this document
[Example.xlsx](https://github.com/nextcloud/previewgenerator/files/7755869/Example.xlsx)

**Comment by st3iny** [comment]
I just tried it on my local instance and it worked just fine. I tested it with the latest version of LibreOffice. 

I suspect that this might be a problem with your setup. Please check your setup of LibreOffice and make sure that `'preview_libreoffice_path' => '/usr/bin/libreoffice'` in your `config.php` points to the right binary.

**Comment by MrLoverLoverMMMM** [comment]
nope, as it always worked it can't be that issue.
Moreover I checked twice.
Can you check the preview-generator with the following config on ubuntu 20.04 and php 8.0 (see sceenshot)
![Sceenshot](https://user-images.githubusercontent.com/17781278/146954928-24e06093-8b0e-4a42-9ab9-11399dda31d4.png)

**Comment by MrLoverLoverMMMM** [comment]
yesterday a new php8.0 update came out, which kinda soluted the problem.
I cannot see the error in the logs anymore.
Thank you very much
