### ISSUE TITLE
Doctrine\DBAL\Exception

### ISSUE THREAD

**Issue by Dedsd** [nextcloud/previewgenerator#283]
```
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Name or service not known in /home/pi/nextcloud/lib/private/DB/Connection.php:87
```

**Comment by st3iny** [comment]
It looks like your Nextcloud server is not able to connect to your database. Please make sure that the host name of your database `postgres` is resolveable.

**Comment by Dedsd** [comment]
Hi! It's strange that nextcloud can't connect to the database with preview generator, since I made the installation and works fine. What do you suggest me to do? Also, what exactly do you mean with resolveable?

**Comment by st3iny** [comment]
"Resolveable" means that the name `postgres` can be translated to an IP address. Does your issue persist?

**Comment by Dedsd** [comment]
Oh, sorry for haven't given you any update on this. In the end was a dns issue. Thanks!
