### ISSUE TITLE
Solution for Docker stateless deployments

### ISSUE THREAD

**Issue by iBobik** [nextcloud/previewgenerator#284]
Docker deployments already run cron.php and does not support crontab customisation.

Could this app hook into Nextcloud's cron.php, so we does not need to create own Docker image?

**Comment by SchoolGuy** [comment]
I would consider this a duplicate of

- https://github.com/nextcloud/previewgenerator/issues/1
- https://github.com/nextcloud/previewgenerator/issues/130
- https://github.com/nextcloud/previewgenerator/issues/205

**Comment by SchoolGuy** [comment]
@st3iny Maybe we can clean this up too? :)

**Comment by st3iny** [comment]
Duplicate of #1, #130 and #205. I will investigate this if I find some time for it.
