### ISSUE TITLE
Support for PHP >=8.1

### ISSUE THREAD

**Issue by goofacz** [nextcloud/previewgenerator#285]
I'm running Nextcloud 23 on Arch Linux with PHP v8.1.2. I cannot find Preview Generator in Nextcloud's App store. After browsing the code I found that dependency:

https://github.com/nextcloud/previewgenerator/blob/53710babf9de76555822f5f3176af122d002a975/appinfo/info.xml#L27

Do you plan to bump max PHP version anytime soon?

**Comment by st3iny** [comment]
I'll bump the version and master and do some testing. However, keep in mind that Nextcloud v24 will be the first official release that supports PHP v8.1.

**Comment by st3iny** [comment]
Support is included in v4.0.0.
