### ISSUE TITLE
Preview generation for 42MP photos has issues?

### ISSUE THREAD

**Issue by helloha82** [nextcloud/previewgenerator#294]
Preview generation with JPG images from my Sony A7R iii at 42Megapixels seems to have issues.

It can generate previews from the portrait shots at 5304px width by 7952px height.

But not when the images are in landscape at 7952px width and 5304px height.

Previews from the RAW's with the _Camera RAW Previews_ app has no isses.

Greets!
K.

**Comment by lockeftw** [comment]
The recomendation of adding or changing the parameter `preview_max_memory' => 256 `in config.php solved this Issue for me
[[[Bug]: Nextcloud cannot create previews for jpg images 34 MP or larger](https://github.com/nextcloud/server/issues/31284#)](https://github.com/nextcloud/server/issues/31284)

**Comment by st3iny** [comment]
@helloha82 Could you please try what @lockeftw suggested and report if it fixes your issue?

**Comment by helloha82** [comment]
> @helloha82 Could you please try what @lockeftw suggested and report if it fixes your issue?

Thanks! This was the fix!
