### ISSUE TITLE
Webp

### ISSUE THREAD

**Issue by killiandt** [nextcloud/previewgenerator#295]
Hello,
the generation of thumbnails does not work with .webp files.
Does anyone have a solution?

Thanks
Have a nice day
Sincerely

**Comment by st3iny** [comment]
Webp previews should work out of the box. You just have to make sure that your version of GD also supports them.

Note that animated webp images do not work at the moment (ref https://github.com/nextcloud/server/issues/30029).

**Comment by killiandt** [comment]
![webp1](https://user-images.githubusercontent.com/104907952/168092993-98e9782f-8ef4-4b23-b029-1b967f6a6d61.png)

**Comment by st3iny** [comment]
GD (or libgd) is the library that we use to generate previews. Please run `php -r 'var_dump(gd_info());'` on your server and post the output. Also, please tell me which version of PHP you are using.

**Comment by st3iny** [comment]
The snap package is out of my reach. I'm very sorry that I can't help you any further. My guess is that they package an old version of libgd that doesn't support webp images.

I saw that you already reached out to the maintainers of the snap package (ref https://github.com/nextcloud-snap/nextcloud-snap/issues/2069).

Closing because this can't be fixed by me.

**Comment by moritz76** [comment]
Hello,

I am facing the same issue. (No snap installation)

Nextcloud Version: 23.0.5
php: 7.4
nginx: 1.21.6

Here is the output from the command:
php -r 'var_dump(gd_info());'

array(14) {
  ["GD Version"]=>
  string(5) "2.3.0"
  ["FreeType Support"]=>
  bool(true)
  ["FreeType Linkage"]=>
  string(13) "with freetype"
  ["GIF Read Support"]=>
  bool(true)
  ["GIF Create Support"]=>
  bool(true)
  ["JPEG Support"]=>
  bool(true)
  ["PNG Support"]=>
  bool(true)
  ["WBMP Support"]=>
  bool(true)
  ["XPM Support"]=>
  bool(true)
  ["XBM Support"]=>
  bool(true)
  ["WebP Support"]=>
  bool(true)
  ["BMP Support"]=>
  bool(true)
  ["TGA Read Support"]=>
  bool(true)
  ["JIS-mapped Japanese Font Support"]=>
  bool(false)
}
