### ISSUE TITLE
Hetzner Storage Share (hosted Nextcloud) Webcron

### ISSUE THREAD

**Issue by devnoname120** [nextcloud/previewgenerator#299]
[Hetzner Storage Share](https://www.hetzner.com/storage/storage-share#pricing) (**only 3.90€ for 1 TB** with RAID redundancy and regular backups!) is configured with a PHP `max_execution_time` set to **10800**, this is **3 hours** (!)

Would it be possible to add a Webcron for the hosted Nextcloud instances that have a high `max_execution_time`?

Thank you 🙏

**Comment by st3iny** [comment]
That is a legitimate use case for implementing background jobs. This has been on my list for a long time but I can't make any promises.

**Comment by st3iny** [comment]
This feature is tracked in https://github.com/nextcloud/previewgenerator/issues/1.

**Comment by devnoname120** [comment]
Quick update, the following three commands are now available on the Hetzner administration page:

```
preview:generate-all %USER%
preview:pre-generate
preview:reset-rendered-texts
```

I'm not entirely sure whether `preview:pre-generate` is run as part of the CRON job or if it needs to be run manually by the user.

**Comment by st3iny** [comment]
`preview:pre-generate` has to be run periodically through a cron job. `preview:generate-all` has to be run once (after installing the app).

**Comment by n00bster** [comment]
> That are great news!
> 
> `preview:pre-generate` has to be run periodically through a cron job. `preview:generate-all` has to be run once (after installing the app).

How did you add the command to the "hetzner storage share" to a "cronjob" there?

**Comment by st3iny** [comment]
I have no experienced with Hetzner managed services but you could have a look at the [official cron job manager docs](https://docs.hetzner.com/konsoleh/account-management/configuration/cronmanager).
