### ISSUE TITLE
MKV video preview generation crashes the process

### ISSUE THREAD

**Issue by ralfi** [nextcloud/previewgenerator#306]
Hi there,

on my NC24 setup everything including mp4 video preview generation works but using mkv container (e.g. generated by tvheadend or converted with ffmpeg) crashes the process. Is mkv container supported?

Thanks a lot.

**Comment by st3iny** [comment]
It should work as long as you have the `OC\Preview\Movie` provider enabled. It could be caused by an unsupported video codec inside the container.

Please provide more information (e. g. relevant config sections, nextcloud log) if you want me to debug this further.

**Comment by ralfi** [comment]
Hi @st3iny thanks for reply,

this is the relevant preview section from config.php ...

![ksnip_20221004-114039](https://user-images.githubusercontent.com/294423/193787619-b154f84e-7456-4a2f-a3cd-4d6594efb471.png)

and here is a the mediainfo output from a sample record...

![ksnip_20221004-114437](https://user-images.githubusercontent.com/294423/193788502-2c1913fc-0ec6-4e86-9e57-1b3f0bc0a4c0.png)

Thanks a lot in advance.

**Comment by joshtrichards** [comment]
> crashes the process. 

Crashes in what way precisely?

> OC\\Preview\\MKV

Try `OC\Preview\Movie`

Though I'm still interested in the specifics of the crash you're seeing.

**Comment by ralfi** [comment]
Hi josh, never seen this, pls close the issue
