### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by some-git-user** [nextcloud/previewgenerator#308]
Some images are not displayed in the list preview.
If I open the image preview I receive "Error loading IMG_....JPG" message.

The error images are not any special among the others. No higher resolution, or size.
If I download these error images, I can open them in any picture preview application without problems.

My Nextcloud version is **24.0.3**

I already checked on the `user_usage_report` app, but it's not installed.
My 'preview_max_memory' is set to 512 `'preview_max_memory' => '512', `

Also tried to regenerate the previews:
`Remove the folder /mnt/sdb/nextcloud-data/appdata_/preview`
`sudo -u www-data php7.4 occ files:scan-app-data (this will reset the preview generation logs)`
`sudo -u www-data php7.4 occ preview:generate-all`

I checked on the nextcloud.log and found following message for every error image:
`"message":"file_put_contents(/mnt/sdb/nextcloud-data/appdata_oc28yh33gjzb/preview/4/7/3/4/f/5/8/2646898/1536-2048-max.jpg): failed to open stream: No such file or directory at /usr/share/nginx/nextcloud/lib/private/Files/Storage/Local.php#296"`

![Screenshot_2022-08-05_09-34-47](https://user-images.githubusercontent.com/65288184/183027587-40fe2758-c388-476c-aef6-713b92ba6d6e.png)
![Screenshot_2022-08-05_09-40-16](https://user-images.githubusercontent.com/65288184/183027592-010b2879-370e-4565-a062-ee661c9585d6.png)

**Comment by st3iny** [comment]
I just tried to reproduce it on the exact same version that you are using and it worked fine.

Could you please provide more information from your Nextcloud log (e. g. the trace). Ideally, you could post the whole related JSON object from your nextcloud.log file.

**Comment by some-git-user** [comment]
I can't tell you why, but for now all previews are working fine.
I didn't change anything in the setup, beside regular updates like Nextcloud 24.0.5 and preview generator 5.1.0.

Following cronjobs are running for www-data user:
```
0 0 * * *   php7.4 /usr/share/nginx/nextcloud/occ preview:generate-all
0 1 * * *   php7.4 /usr/share/nginx/nextcloud/occ files:scan --all > /dev/null 2>&1
*/15 * * * * php7.4 /usr/share/nginx/nextcloud/occ preview:pre-generate
*/15 * * * * php7.4 /usr/share/nginx/nextcloud/occ files:scan --unscanned --all > /dev/null 2>&1
```

Maybe anything I can optimize with the cronjobs?

**Comment by st3iny** [comment]
You could remove the `files:scan` entries because they are kind of expensive to run. They should only be in your cron jobs if you really need them (e. g. using external storage).

**Comment by st3iny** [comment]
> I can't tell you why, but for now all previews are working fine.
I didn't change anything in the setup, beside regular updates like Nextcloud 24.0.5 and preview generator 5.1.0.

That's great to hear! There probably were some changes in the server that fixed your problem.
