### ISSUE TITLE
Failed to generate previews for videos. All Videos. 

### ISSUE THREAD

**Issue by Mars160** [nextcloud/previewgenerator#309]
![image](https://user-images.githubusercontent.com/74127225/187929653-8a390164-f8c0-4d73-8352-d8eaf3b840f2.png)
Here is my config.php file

**Comment by invario** [comment]
> ![image](https://user-images.githubusercontent.com/74127225/187929653-8a390164-f8c0-4d73-8352-d8eaf3b840f2.png) Here is my config.php file

It should be enabledPreviewProviders


Note the letter D in enableD.

**Comment by st3iny** [comment]
Thanks for helping out @invario. Please close the ticket if this solves your issue @Mars160.

**Comment by Mars160** [comment]
@invario Thank you!
Changing _enable_ into _enabled_ solved my problem perfectly!
