### ISSUE TITLE
Generate WEBP previews for WEBP files (or at least as JPG)

### ISSUE THREAD

**Issue by RickOrchard** [nextcloud/previewgenerator#314]
I cant believe i'm having to create an issue for this in 2022, but here we go:

Also see https://github.com/nextcloud/viewer/issues/1315

**Currently** for WEBP files, the viewer generates PNG files (who thought that was a good idea?). Resulting in 3~4 MB PNG files where the WEBP original files are a few 100 KB. This is obviously _not desired_, to put it mildly. I have folders filled with WEBP files, resulting in a '90's style excruciating slow browsing experience because of this.

**Desired behaviour**: Fully support WEBP formats by creating previews of the same format.

Info: WEBP and WEBM formats were specifically introduced over a decade ago to replace archaic formats like PNG, BMP, JPG, AVI and MPEG.

**Comment by st3iny** [comment]
The previews themselves are generated by the server. Unfortunately, I have no influence over the logic itself. My app just triggers the generation process.

Please have a look at https://github.com/nextcloud/server/issues/13552 for the feature request.

**Comment by RickOrchard** [comment]
Are you kidding me? I'm starting to wonder if there are any knowledgable people on this topic at Nextcloud at all. Surely you guys understand collaborative infrastructure, but obviously you guys are seriously lacking expertise on topics concerning multimedia. Disappointing. Even if generating WEBP previews is not supported by the software you are using, then at least disable preview generation for that format and serve the raw WEBP files. The current 'solution' serves 'preivew' PNG files that are 6-10x the size of the original, i cant believe how stupendous this is!

**Comment by st3iny** [comment]
I totally agree, that the preview generation is suboptimal in some cases. In the end this is a matter of priorities. Please remember that you can't expect us to implement features for free.

Contributions in this area are always welcome. Feel free to open a PR if you are experienced in this area.

**Comment by RickOrchard** [comment]
Sure. Is that preview-generating library also opensource? If so, can you link to it?

**Comment by RickOrchard** [comment]
I mean, the PreviewGenerator method implements the IPreview interface, but the actual implementation seems to be passed as a parameter. Which function is responsible for calling this class and passing the actual implementation? I will find my way from there.

**Comment by st3iny** [comment]
Take a look at:
- https://github.com/nextcloud/server/blob/048fdabca905746c542cabefc5c0b4684819fdf3/lib/private/Preview/WebP.php
- \OC\Preview\Generator::generatePreviews
- \OC\Preview\Generator::generatePreview
- \OC\Preview\Generator::getExtention

The class \OC\Preview\Generator is located in https://github.com/nextcloud/server/blob/048fdabca905746c542cabefc5c0b4684819fdf3/lib/private/Preview/Generator.php.
