### ISSUE TITLE
User commands to create thumbnails

### ISSUE THREAD

**Issue by demonlibra** [nextcloud/previewgenerator#318]
Is it possible to integrate user commands to create thumbnails for user formats?

E.g. I can create thumbnails for STL files by [minirender](https://github.com/aslze/minirender) with command:
`render -o -- -yaw 30 -tilt 40 -bgcolor 255,255,255 model.stl | convert - model.png`

**Comment by st3iny** [comment]
Unfortunately, this is not possible. You would have to implement your own custom preview provider.

Please have a look at:
- Implement public interface: https://github.com/nextcloud/server/blob/master/lib/public/Preview/IProviderV2.php
- Example provider (Movie): https://github.com/nextcloud/server/blob/master/lib/private/Preview/Movie.php
- Configuring existing preview providers: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/previews_configuration.html
