### ISSUE TITLE
Some images generated with imaginary are incorrect

### ISSUE THREAD

**Issue by janusn** [nextcloud/previewgenerator#323]
Some square preview images generated with command
`$ occ preview:generate-all -vvv`
are a crop of the original images and the aspect ratio are not preserved.
On the other hand, the square preview images generated by web interface of Nextcloud are correctly. They respect the aspect ratios and letterboxed correctly.

Environment:

- Nextcloud docker: linuxserver/nextcloud:latest

> - Nextcloud version 24.0.6
> - previewgenerator version 5.1.0

- imaginary docker: h2non/imaginary:latest

> - Imaginary version 1.2.4

- host OS: DSM 7.1.1-42962 Update 1
- hardware: Synology DS-918+

The content of the config.php:
```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
    'timeout' => 1.5,
  ),
  'filelocking.enabled' => true,
  'datadirectory' => '/data',
  'instanceid' => '<omitted for security>',
  'passwordsalt' => '<omitted for security>',
  'secret' => '<omitted for security>',
  'trusted_domains' => 
  array (
    0 => '<omitted> for security>',
  ),
  'dbtype' => 'mysql',
  'version' => '24.0.6.1',
  'trusted_proxies' => ['swag'],
  'overwrite.cli.url' => '<omitted for security>',
  'dbname' => 'nextcloud',
  'dbhost' => '10.27.0.40:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '<omitted for security>',
  'dbpassword' => '<omitted for security>',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'files_excludedirs',
  ),
  'default_phone_region' => 'GB',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'No.Reply',
  'mail_domain' => '<omitted for security>',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '<omitted for security>',
  'mail_smtpport' => '465',
  'mail_smtpname' => '<omitted for security>',
  'mail_smtppassword' => '<omitted for security>',
  'preview_max_x' => null,
  'preview_max_y' => null,
  'jpeg_quality' => '60',
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => [
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\OpenDocument',
    'OC\Preview\Krita',
    'OC\Preview\Imaginary',
  ],
  'preview_imaginary_url' => 'http://imaginary:9000',
);
```

The previewgenerator settings:
```
$ php /config/www/nextcloud/occ config:app:get previewgenerator squareSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator widthSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator heightSizes
64 256 1024
```

A sample of an original image: 
![200042733-9284683a-bf54-4180-b0e4-63faba51b630](https://user-images.githubusercontent.com/21253783/200947427-4945f8ae-507d-40b1-9771-d7bdfbd67f7f.jpg)

The preview generated for both grid view and detailed view on the Files pane.
![200042792-55a96c2c-3ce2-4390-b3f3-6d4aa512268d](https://user-images.githubusercontent.com/21253783/200947467-46eb1b8a-ee93-49ec-a672-23dc670ebe06.jpg)

Another example of an original image:
![200041760-34ad1f18-4f18-42bc-8549-486b11ad6d82](https://user-images.githubusercontent.com/21253783/200947494-abffb122-529f-4171-a67d-6f8ac848c65e.jpg)

The preview generated for both grid view and detailed view on the Files pane.
![200042005-39e74c9b-b6ce-4833-a9f8-e82b23ada8c3](https://user-images.githubusercontent.com/21253783/200947532-ee75f8f6-6225-42bd-8b31-34f6d4c648ca.jpg)

**Comment by st3iny** [comment]
I see, that you are persistent.

I'll try to reproduce it. However, I suspect this being either a bug in the server or the imaginary upstream.

**Comment by szaimen** [comment]
@janusn which Imaginary version are you running?

**Comment by szaimen** [comment]
Can you for a test check if it works with the `nextcloud/aio-imaginary:latest` image corrrectly?

**Comment by janusn** [comment]
@szaimen The version of imaginary is 1.2.4.

**Comment by szaimen** [comment]
Yeah, so to make it work correctly, it is required to build imaginary from master since no new release was pushed since two years. That is what we are doing with the `nextcloud/aio-imaginary:latest` image. Hence my question if you could test with that.

**Comment by janusn** [comment]
@szaimen Thanks for the pointer. I have replaced the container from the image _h2non/imaginary:latest_ with the image _nextcloud/aio-imaginary:latest_. Unfortunately, it still produces strange distorted previews.

In fact, you can see the previews of the build-in stock photos generated from _aio-imaginary_ are distorted, such as

- /[User]/files/Photos/Birdie.jpg
- /[User]/files/Photos/Frog.jpg
- /[User]/files/Photos/Gorilla.jpg
- /[User]/files/Photos/Toucan.jpg

but the previews of the following photos are correct:

- /[User]/files/Photos/Library.jpg
- /[User]/files/Photos/Nextcloud community.jpg
- /[User]/files/Photos/Vineyard.jpg

The version of the aio-imaginary:
```
$ imaginary --version
dev
```

**Comment by szaimen** [comment]
Right. Then maybe @CarlSchwan has an idea?

**Comment by st3iny** [comment]
> On the other hand, the square preview images generated by web interface of Nextcloud are correctly. They respect the aspect ratios and letterboxed correctly.

I couldn't reproduce it. For me it's the exact other way around.

I only enabled the Imaginary provider to be able to isolate the issue. Both square previews generated by `generate-all` are fine. Square previews generated by the web interface are weird and look like your examples.

I'm currently investigating the server code to find a difference between both calls to the Preview API.

**Comment by szaimen** [comment]
If I remember the response of Carl correctly, the maintainer of Imaginary submitted in the last moment a commit that broke something. Not sure if it is the same issue though. Probably it is then this: https://github.com/h2non/imaginary/pull/382/commits/234d1fecb7e0bc49f51f6f2152ba77c1d1388fa6
https://github.com/nextcloud/server/search?q=X-Image-Width

**Comment by st3iny** [comment]
I tested some more and noticed that the previews are only broken if the source image is smaller than the actual preview.

E.g. Supplying an Image with 8000x6000 produces correct results. Supplying an image with 640x480 produces weird results because Nextcloud asks for a preview of 1024x1024.

**Comment by st3iny** [comment]
Bingo! 

@szaimen This is correct. I added debugging code to Imaginary which dumps each generated image to a file and they are correct. It seems like our server does not parse the width and height values correctly and thus distorts the image. 

This should be fixable by parsing both headers.

**Comment by szaimen** [comment]
> This should be fixable by parsing both headers

Indeed but only if the header was specified to be emitted, correct?

**Comment by szaimen** [comment]
See https://github.com/h2non/imaginary/pull/382/files#diff-77ed712c0c6f7b52686415504853bc522f5f0ee3e9e0399cfd60a48813aa6aaeR110

**Comment by szaimen** [comment]
So rather fail if one of these headers was not found instead of generating false previews?

**Comment by st3iny** [comment]
Yes, but I came up with a workaround. The image is now parsed when width and height are not specified. This has a minor performance impact but there is no way around it. We need to have the exact width and height values or previews will be distorted.

I'm also planning to amend the documentation with a warning to alert admins to use the `-return-size` flag. 
Ref https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews

**Comment by szaimen** [comment]
Fine by me 👍

**Comment by st3iny** [comment]
> However I am thjnking about tweaking the container so that `-return-size` is added by default. WDYT?

Great idea!

**Comment by szaimen** [comment]
Let me have a look at this then :)

**Comment by szaimen** [comment]
Should we improve the docs on this? Shall I do or will you do @st3iny ? :)

**Comment by janusn** [comment]
For the document, please mention the registry "nextcloud/aio-imaginary". Otherwise people like me will still get the wrong image. Thanks a ton!

**Comment by szaimen** [comment]
Yes, will do. Thanks for bringing this up!

**Comment by janusn** [comment]
@szaimen  Thanks. I have forgotten to mention. It is better to give the imaginary a real version number to be returned by the following command as well. It is much easier to report any bug on it.
`$ imaginary --version`

**Comment by szaimen** [comment]
I see, however since this is built staight from their github source code, I don't know how to apply that change...

**Comment by st3iny** [comment]
> Should we improve the docs on this? Shall I do or will you do @st3iny ? :)

I'm on it.

**Comment by szaimen** [comment]
Thanks! :)
