### ISSUE TITLE
Slow cron.php execution after enabling Preview Generator Plugin

### ISSUE THREAD

**Issue by Cebrain** [nextcloud/previewgenerator#324]
Hi,

i have a problem after enabling Preview Generator Plugin.
The Cron.php job runs very long after generating the plugin and creating the previews.
Everything else is fine.

There is already an issue in the nextcloud server repo but not many updates in the last time
https://github.com/nextcloud/server/issues/24401

Any way to fix this problem or is this known?

Setup:
Nextcloud Apache Docker (25.0.1)
MariaDB
Redis
imaginary generated previews (tested also with default)

I have many photos on an external storage (about 10.000)

Config of Preview Generator:
./occ config:app:set --value="32 64 1024"  previewgenerator squareSizes
./occ config:app:set --value="64 1024" previewgenerator widthSizes
./occ config:app:set --value="64 1024" previewgenerator heightSizes

**Comment by Cebrain** [comment]
After generating the previews, there are many "unscanned" paths,  i checked it with the following command from the github issue
https://github.com/nextcloud/server/issues/24401#issuecomment-758200211

`SELECT path FROM oc_filecache WHERE (size < 0) ORDER BY fileid DESC;`

Output:
`
...| appdata_occpy53sbnk7/preview/8/5/d/b/5/a/3 |
| appdata_occpy53sbnk7/preview/8/5/d/b/5/a   |
| appdata_occpy53sbnk7/preview/8/5/d/b/5     |
| appdata_occpy53sbnk7/preview/6/b/7/9/c/3/b |
| appdata_occpy53sbnk7/preview/6/b/7/9/c/3   |
| appdata_occpy53sbnk7/preview/6/b/7/9/c     |
| appdata_occpy53sbnk7/preview/6/b/7/9       |
| appdata_occpy53sbnk7/preview/d/2/b/5/2/c/e |
| appdata_occpy53sbnk7/preview/d/2/b/5/2/c   |
| appdata_occpy53sbnk7/preview/d/2/b/5/2     |
| appdata_occpy53sbnk7/preview/d/2/b/5       |
| appdata_occpy53sbnk7/preview/e/2/7/a/7/e/d |
| appdata_occpy53sbnk7/preview/e/2/7/a/7/e   |
| appdata_occpy53sbnk7/preview/e/2/7/a/7     |
| appdata_occpy53sbnk7/preview/e/2/7/a       |
+--------------------------------------------+
551 rows in set (0.000 sec)
`

When i run "occ files:scan-app-data" the paths getting cleared. After running the cron job the paths are back in the table?
Is this a normal behavior? Could this be related?

**Comment by st3iny** [comment]
I'm sorry but this isn't related to PreviewGenerator because the app doesn't integrate with cron jobs at all.
