### ISSUE TITLE
pre-generate only ever returns "Command is already running."

### ISSUE THREAD

**Issue by FrankelJb** [nextcloud/previewgenerator#328]
I'm running Nextcloud 25 in a Kubernetes cluster. This is all running fine and has been for over a year. I ran previewgenerator some time ago. However, I've just noticed that running `./occ preview:pre-generate` only ever returns "Command is already running."

I've tried to restart the containers, redeploy them, disable and re-enable previewgenerator all to no avail. Is there some way to force the pre-generate? I've tried to read the code to see if I can delete something. However, I'm not very familiar with how Nextcloud extensions work.

**Comment by f1ana** [comment]
I just started encountering this as well.  Not really sure how to proceed with fixing the issue.

**Comment by st3iny** [comment]
This sound like the generation process got stuck at some point and didn't reset the parallel processing lock. Usually, that should only happen if the previewgenerator process was interrupted.

I could add a new command to reset the pid lock in case of an error.

In the meantime, you can reset the lock manually by running the following query:

```sql
DELETE FROM
  oc_appconfig
WHERE
  appid = 'previewgenerator'
  AND configkey = 'pid';
```

**Comment by st3iny** [comment]
Enhancement to add a command to reset the lock is tracked in https://github.com/nextcloud/previewgenerator/issues/118.
