### ISSUE TITLE
With previewgenerator cron job aborted "Call to a member function getUID()"

### ISSUE THREAD

**Issue by NobodyO815** [nextcloud/previewgenerator#331]
Hello,

if the previewgenerator is activated, my cron won't run anymore...

root@cloud:/home/administrator# sudo -u www-data php -f /var/www/nextcloud/cron.php
Error: Call to a member function getUID() on null in /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:154
Stack trace:
#0 /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php(56): OCA\Maps\Service\PhotofilesService->updateByFileNow()
#1 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run()
#2 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(58): OCP\BackgroundJob\Job->start()
#3 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(48): OCP\BackgroundJob\QueuedJob->start()
#4 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\QueuedJob->execute()
#5 {main}

after disabling again everything is fine.

**Comment by NobodyO815** [comment]
I've tested a little:
It seemst to be only in combination with the maps App - without maps no problem at the moment...

Only Maps - ok
Only previewgenerator -ok
both - not ok.

**Comment by st3iny** [comment]
Yeah, should be fixed in the newest version of Maps. Which versions of Nextcloud and Maps are you running?

**Comment by st3iny** [comment]
This is fixed by updating the Maps app to at least v0.2.0. Make sure to use a recent version of Nextcloud, in case the update isn't available.

Ref https://github.com/nextcloud/maps/issues/722
