### ISSUE TITLE
Generate thumbnail preview for videos

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/previewgenerator#334]
I'm not sure if this would be a nextcloud photos isssue or here

It would be nice to have previews on .mov, mp4

![image](https://user-images.githubusercontent.com/59488153/212562243-2d07a8ca-e7f1-4657-a9c9-631d83069a0e.png)

**Comment by st3iny** [comment]
This is already possible. Please enable the `OC\Preview\Movie` preview provider and install ffmpeg on your server.

Ref https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#previews

**Comment by andyxheli** [comment]
Oh thank you! I didn't see it im sorry,.
