### ISSUE TITLE
triangle sign for video files 

### ISSUE THREAD

**Issue by marcolam** [nextcloud/previewgenerator#347]
video files and photos have the same look,when clicking a thumbnail you don’t know it’s a video and it starts downloading(some video formats don’t support online streaming,like m2ts)
maybe it’s a nextcloud issue ?thanks!

**Comment by st3iny** [comment]
Thank you for your report.

This has to be implemented in the core repository. I'm closing it in favor of https://github.com/nextcloud/server/issues/33555.
