### ISSUE TITLE
Possibility to specify the path to ffmpeg

### ISSUE THREAD

**Issue by g-work** [nextcloud/previewgenerator#348]
Is there a possibility to specify the path to ffmpeg?

I’m on a Synology Diskstation and there is a preinstalled ffmpeg which seems to struggle generating previews vom h.265 videos. I would like to use the version provided by the SynoCommunity, but previewgenerator always uses the preinstalled one.

**Comment by szaimen** [comment]
It will be possible with Nc26 due to https://github.com/nextcloud/server/pull/36225
