### ISSUE TITLE
PHP 8.2 flooding log with error messages

### ISSUE THREAD

**Issue by jacotec** [nextcloud/previewgenerator#366]
With PHP8.2, previewgenerator floods the log with error messages:

`Using ${var} in strings is deprecated, use {$var} instead at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php#204`

**Comment by st3iny** [comment]
Thanks for the report.

This is already know. Fixes are at https://github.com/nextcloud/previewgenerator/pull/365 and https://github.com/nextcloud/previewgenerator/pull/367.
