### ISSUE TITLE
Can't generate thumbnails for video and office files

### ISSUE THREAD

**Issue by Mars160** [nextcloud/previewgenerator#371]
This is part of my config.php
![image](https://user-images.githubusercontent.com/74127225/229817496-4d3702ea-38be-4fdd-910b-f8bb51a662a9.png)

I'm running nextcloud using php-fpm behind Nginx.
The user who runs nextcloud is nextcloud:nextcloud. And the nextcloud user can excute ffmpeg.
![image](https://user-images.githubusercontent.com/74127225/229813545-e8b9785f-14ee-4956-b6a0-3c0ddd58e119.png)

No error log found. When I excute 'occ preview:generate-all -vvv', it will stop and generate thumbnails for PDF, JPG and TXT but MP4, MKV.

|APP|Version|
|----|-------|
|Nextcloud|26.0.0|
|PreviewGenerator|5.2.2|
|FFmpeg|6.0|
|PHP|8.1.17|
|php-imagick|3.7.0|
|imagemagick|7.1.1.5|

Can you help me?

![image](https://user-images.githubusercontent.com/74127225/229816845-31bacdca-e53d-4520-97ed-2341a87e7871.png)

**Comment by hdlineage** [comment]
you dont have MKV or MP4 in your "enablepreviewproviders"

**Comment by st3iny** [comment]
Thanks Teemo :D

I suppose this issue has been resolved?

**Comment by Mars160** [comment]
Sadly no 😢
![Uploading image.png…]()

**Comment by Mars160** [comment]
Actually, no
This is the preview folder.
There is no thumbnails for the MP4 file.

![image](https://github.com/nextcloud/previewgenerator/assets/74127225/944e1823-186c-4d00-a84b-b415d76ec4fb)

**Comment by Mars160** [comment]
@st3iny Yeah, I added both MP4 and MKV in config.php
![image](https://github.com/nextcloud/previewgenerator/assets/74127225/91c821c2-f251-4263-9c92-dd1bdb065a05)

**Comment by Mars160** [comment]
It looks like it didn't follow my config.php file to generate thumbnails.
It only generate thumbnails for the default types

**Comment by joshtrichards** [comment]
@Mars160 

`OC\Preview\Movie` will handle the preview generation for [all files with  `video/*` mime types](https://github.com/nextcloud/server/blob/4b85a886207c2a5d2faffc055e7662ea99118c1a/lib/private/PreviewManager.php#L410).

However, you may need to set the path for `ffmpeg` in some environments:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#preview-ffmpeg-path

If Nextcloud doesn't find the ffmpeg binary on its own, it disables the movie preview parameter (since it can't generate them).

**Comment by Mars160** [comment]
> @Mars160 
> 
> `OC\Preview\Movie` will handle the preview generation for [all files with  `video/*` mime types](https://github.com/nextcloud/server/blob/4b85a886207c2a5d2faffc055e7662ea99118c1a/lib/private/PreviewManager.php#L410).
> 
> However, you may need to set the path for `ffmpeg` in some environments:
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#preview-ffmpeg-path
> 
> If Nextcloud doesn't find the ffmpeg binary on its own, it disables the movie preview parameter (since it can't generate them).

Thanks for your kind reply.

I reinstalled the whole environment and nextcloud. This issue is finished. I don't know what was changed but the problem is solved
