### ISSUE TITLE
v5.2.2 is ignoring preview provider Imaginary

### ISSUE THREAD

**Issue by drhirn** [nextcloud/previewgenerator#373]
NC: 26.0.0
Preview-Generator: 5.2.2

Three weeks ago i let previewgenerator generate some thousand previews of my files using Imaginary. Did work very well.

Since on of the last updates, it's completely ignoring my wish to use the Imaginary preview provider.

config.php:
```
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Imaginary',
    1 => 'OC\\Preview\\GIF',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\MP3',
    5 => 'OC\\Preview\\PNG',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\XBitmap',
    8 => 'OC\\Preview\\BMP',
    9 => 'OC\\Preview\\OpenDocument',
    10 => 'OC\\Preview\\Krita',
    11 => 'OC\\Preview\\HEIC',
    12 => 'OC\\Preview\\PDF',
    13 => 'OC\\Preview\\MP4',
    14 => 'OC\\Preview\\MKV',
    15 => 'OC\\Preview\\AVI',
    16 => 'OC\\Preview\\Movie',
  ),
  'preview_imaginary_url' => 'https://imaginary.example.com/',
```

Have there been any changes?

**Comment by drhirn** [comment]
Seems working again.

**Comment by cburlacu** [comment]
Did you change anything to work? 
I have v5.2.4 running on NC 26.0.1 and it doesn't use Imaginary...

**Comment by st3iny** [comment]
No, I didn't change anything regarding that recently. There might have been some changes in server that I'm not aware of.

**Comment by drhirn** [comment]
> Did you change anything to work? I have v5.2.4 running on NC 26.0.1 and it doesn't use Imaginary...

No, I didn't. Besides updates to Previewgenerator and Nextcloud. Now using the same version numbers than you.
Should I reopen this issue?

**Comment by cburlacu** [comment]
Thank you all for the reply. I am not sure if this issue should be reopened.

I was trying to regenerate all the thumbnails using `preview:generate-all` and didn't seem to use Imaginator... 
https://github.com/nextcloud/previewgenerator/issues/312#issuecomment-1528798259
