### ISSUE TITLE
Limit pre-generate to specific paths

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/previewgenerator#374]
It's great that the `preview:generate-all` command has the option to specify paths! But it would be even better if the same same was also possible with pre-generation. This would make it possible to generate previews only for some folders during normal operation - and not only during the initial import. 

So what do you think about adding the `[--path=PATH ...]` option also to the `preview:pre-generate` command?

I'm not sure how much of the code from [Generate.php](https://github.com/nextcloud/previewgenerator/blob/35ad273f184369c9773ac18f3d91c9218c4ae3cd/lib/Command/Generate.php) can be reused. Maybe this is not so much of an effort?

**Comment by st3iny** [comment]
I like the idea. However, I can't make any promises and contributions are always welcome.

**Comment by st3iny** [comment]
Closing in favor of https://github.com/nextcloud/previewgenerator/issues/76.
