### ISSUE TITLE
How do I add a cron job?

### ISSUE THREAD

**Issue by JL102** [nextcloud/previewgenerator#386]
```
Add a (system) cron job for  ./occ preview:pre-generate
```

I'm using Nextcloud AIO. How do I add a cron job for step four? Do I have to manually edit cron.php? Or does it do this automatically?

Thanks!

**Comment by st3iny** [comment]
@szaimen Who does one add a custom cron job in AIO?

**Comment by st3iny** [comment]
@JL102 You have to manually add a cron job. Usually, this is done on the system itself via a cron daemon. I'm not sure how to do this with AIO.

**Comment by szaimen** [comment]
@JL102 see https://github.com/nextcloud/all-in-one/discussions/542

**Comment by JL102** [comment]
Thanks! Closing.
