### ISSUE TITLE
Possible to support 3D Files?

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/previewgenerator#388]
Hi,

at the moment Files like STL, 3MF, OBJ and more are only supported over external Scripts. May you can support it in the Preview Generator?

Thanks

**Comment by st3iny** [comment]
Thanks for the feature request.

I'm closing this as the actual preview generation logic is not part of this repository. Instead, they are implemented in the server repository. Please consider opening a [feature request](https://github.com/nextcloud/server/issues/new?assignees=&labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md) there.

Your contributions are always welcome if your are knowledgeable with those file formats and php. It would also be possible to program a custom app for generating those previews.
