### ISSUE TITLE
overwriting nextcloud - config.php with default after any update

### ISSUE THREAD

**Issue by tobefrank1** [nextcloud/previewgenerator#406]
Hello,

trying  to get a preview of office docs like .doc, .xlsx, .ods ..., nothing likes to work . 
PDF, jpeg ... are shown as icons as it should be. 
The strange thing is that I may see a preview in the dashboard (.ods) or top as a recently viewed, but never as file icon.  

I tried several tutorials for several times on several new installed nextcloud versions since V22.
I am on 27  now and the issue persists.   I really do not know what I miss. 

Now I noticed that after every app update (any app) my modifications of the config.php are over written with default settings in the preview section, deleting my settings for OpenDocument etc. ! 
As far as I can tell, it is the preview section only! And that might explain some of the observation. 
One can stop that by adding a 

 'config_is_read_only' => true,

but that will stop any update from going through!  Leaving it out gets you to square one. 

I do not understand the reason why a modified config file is changed to default without any warning nor how I may get my config to default. 

I am grateful for every idea out there. 

My preview section of config.php looks like this:

'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\OpenDocument',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOfficeDoc',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\Image', 
    8 => 'OC\\Preview\\Photoshop',
    9 => 'OC\\Preview\\TIFF',
   10 => 'OC\\Preview\\SVG', 
   11 => 'OC\\Preview\\Font',
  12 => 'OC\\Preview\\MP3',
   13 => 'OC\\Preview\\Movie',
   14 => 'OC\\Preview\\MKV',
   15 => 'OC\\Preview\\MP4',
   16 => 'OC\\Preview\\AVI',  
  ),

**Comment by joshtrichards** [comment]
Do you have any other files within the `config` folder within your Nextcloud installation directory? Nextcloud will merge together all config files it finds... so if there are conflicts...

What does the output of `occ config:list system` (or equivalent) show?

This app (`previewgenerator`) doesn't touch your config file on its own though. I suppose there could be something in core (Server), but my gut tells me something else is going on here.

**Comment by joshtrichards** [comment]
I suggest posting your query over at the Help Forum - https://help.nextcloud.com since this channel isn't setup for general support. We only track bugs here. 

When you post there, I suggest using the output of `occ config:list system` since it parses your condition and is also multi-config aware.
