### ISSUE TITLE
initial generation command

### ISSUE THREAD

**Issue by petrosmm** [nextcloud/previewgenerator#409]
on [app page](https://apps.nextcloud.com/apps/previewgenerator) it says `./occ preview:generate-all -vvv`
but here in the [README.md](https://github.com/nextcloud/previewgenerator/blob/main/README.md) it says `./occ preview:generate-all` and the first works for me, the second just hangs and looks endless.... which is correct and why the difference?

**Comment by petrosmm** [comment]
verbosity isn't it?

**Comment by st3iny** [comment]
They are both the same. The first variant just prints more verbose output to the console.

**Comment by st3iny** [comment]
That is probably why it seems to hang but it doesn't.

**Comment by petrosmm** [comment]
i feel dumb already, thanks! as an idiot user who didn't notice the commands wasn't working, i recommend you keep the `-vvv`

**Comment by st3iny** [comment]
Don't worry :)
