### ISSUE TITLE
Unwanted office document previews generated?

### ISSUE THREAD

**Issue by jcharaoui** [nextcloud/previewgenerator#419]
When running the `preview:generate-all -vvv` command I can see the app slowly iterating over `.doc`, `.odt` and other "office" documents, at the rate of about one document per second, even though preview generation for these types of document is *not enabled* in `config.php`.

I'm not sure what's going on here. I do have the `richdocuments` app installed.

Because of this, pre-generating the previews on my instance is taking a **massive** amount of time.

**Comment by jcharaoui** [comment]
Possibly related to #410

**Comment by st3iny** [comment]
Are you sure that you disabled the preview provider? The office provider is enabled by default and has to be explicitly excluded from the list.

Please refer to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#enabledpreviewproviders.

**Comment by joshtrichards** [comment]
Nextcloud Office registers its own preview providers. See nextcloud/richdocuments#1335

This will need to get addressed in `richdocuments` / Nextcloud Office. So go upvote nextcloud/richdocuments#1335 I guess. ;-)
