### ISSUE TITLE
GUI interface for first time run and cron necessary

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/previewgenerator#431]
if the admin has no access to command line (using NC SAAS from Hetzner) the installation steps can not be performed.
pls add an GUI.

**Comment by st3iny** [comment]
I see where you are coming from but running the initial generation from the UI is not possible, unfortunately.

It would need to be implemented via a web request which would time out eventually. The initial generation takes very long, potentially days and requests are usually allowed to run for 30 seconds max.

I assume that you can add cron jobs in Hetzner's Nextcloud service. You could add a cron jobs that runs once a year which triggers the initial generation. Then, let it run for a week just to be sure and remove it again. I admit that this solution is a bit hacky but it should work just fine.

### An example to run the initial generation at `2023-12-05 00:00:00`

```cron
0 0 5 12 * php /var/www/occ preview:generate-all
```

(This job will run once a year and should be removed after the first run.)

**Comment by joshtrichards** [comment]
> It would need to be implemented via a web request which would time out eventually. The initial generation takes very long, potentially days and requests are usually allowed to run for 30 seconds max.

Maybe we could move this system cron task to a one-tiime Nextcloud managed Background job: https://docs.nextcloud.com/server/latest/developer_manual/basics/backgroundjobs.html#heavy-load-and-time-insensitive :thinking:

**Comment by st3iny** [comment]
Implementing a GUI is not something I'm interested in developing or maintaining. I'll close this issue as the original problem has been solved by Hetzner implementing a web UI for occ.
