### ISSUE TITLE
Need support for Apple HEIF and HEIC for Nextcloud

### ISSUE THREAD

**Issue by myownway888** [nextcloud/previewgenerator#432]
It takes a lot of time for conversion to happen and also drains battery so please add the Apple High Efficiency format to make our and phone's lives easy :)

**Comment by th0rgall** [comment]
Do you mean that you don't want previews to be generated for .HEIC/.HEIF media files? Perhaps this is configurable, if not, this is probably a request for such a setting to be added?

**Comment by st3iny** [comment]
Or is this about generating previews for HEIC files? Because this is already implemented via Imaginary.

**Comment by myownway888** [comment]
It’s about generating the previews, I am not very good at coding and stuff by the way. I was searching online for this and found that there is no direct support (install an app or plugin and good to go kinda stuff). If you guys can help me through I would really appreciate that.

**Comment by myownway888** [comment]
> Do you mean that you don't want previews to be generated for .HEIC/.HEIF media files? Perhaps this is configurable, if not, this is probably a request for such a setting to be added?

I want HEIC/.HEIF preview to be automatically generated without opening the configuration for people like me with less coding knowledge. This is a request to add such settings 🙏.

**Comment by bcutter** [comment]
I want to step in and add me to the requirements list. Currently with v27.1.7.2 previews are not shown for untouched HEICs at all - no matter where (web, iOS app etc.). Not even when opening a file, which is a different behavior to the past, where the preview was shown at least once a file was opened (iOS app for example).

HEIC previews not generated at all:
- at `/apps/photos/`
![grafik](https://github.com/nextcloud/previewgenerator/assets/13799156/9bed0120-dd69-4ada-8951-339d64909651)

- at `/apps/files/`
![grafik](https://github.com/nextcloud/previewgenerator/assets/13799156/6be23725-6508-4de5-8e11-b2cd4870dbcb)

- same on the iOS app in the media tab

So now I read previews for HEICs should already work? Where to check the configuration for that? What to I probably need to install on my bare metal NC server?

**Comment by th0rgall** [comment]
Hey @bcutter, as you can read in the posts above, you need to install Imaginary. My understanding is that the preview generator app integrates with Imaginary to generate previews for .HEIC files, once Imaginary is installed.

Imaginary comes as an optional feature with Nextcloud AIO, but if you're running a bare metal setup, you will probably have to install and configure it yourself. Check this blog post which seems to cover your situation: https://okxo.de/speed-up-nextcloud-preview-generation-with-imaginary

**Comment by bcutter** [comment]
Really interesting article. I took a deeper look at all the stuff needed. And wow, that seems to add a lot of complexity to the preview chain compared the (originally install, configure once and forget about it) preview_generator app looking at https://github.com/h2non/imaginary?tab=readme-ov-file#prerequisites and https://github.com/h2non/imaginary?tab=readme-ov-file#installation. I don't use Docker so I was looking at https://github.com/h2non/imaginary?tab=readme-ov-file#libvips as probably most straight forward way to use on a Raspberry Pi OS (Debian based). Unfortunately running that install script gives
```
Could not find libvips using a PKG_CONFIG_PATH of ':/usr/local/lib/pkgconfig:/usr/lib/pkgconfig'
Detected Debian Linux 'buster'
Sorry, I don't yet know how to install libvips on Debian-based buster
```
Even a `sudo apt install libvips` before (installed `libvips42`) was working the install script still gives the same result. I was thinking about building libvips from source according to https://www.libvips.org/install.html, but that makes a HELL of needed other stuff including a dev/build environment - and at the end it maybe won't run too.

So for HEIC previews this is my specific requirement situation:
1. NC preview generation: imaginary REPLACES preview generator app (according to https://okxo.de/speed-up-nextcloud-preview-generation-with-imaginary/)
2. Imaginary needs libvips (or several other container platforms)
3. Libvips can not be installed from apt, for building from source several other stuff is needed

Even I will update the OS in the next months (Buster ends LTS in 06/2024) and step 3 would work then with Bullseye, according to the install script https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh latest Bookworm is not supported (yet). Ah it's a mess. So, ahm... sorry, I think that's all in all a bit too much for "just" having HEIC previews (again). And come on, for an average Nextcloud part-time admin that's way too complicated. It should really be implemented in an app _somehow_. Install + use out of the box.

---

> My understanding is that the preview generator app integrates with Imaginary

No it doesn't. Imaginary replaces preview generator, see 1. above. It just abuses preview generator app once for generating previews for existing images:

> Nextcloud does not use the Preview Generator to generate the previews, but Imaginary.
> You can deactivate or delete the preview generator after the build

---

So, back to business not wasting of admin hours: **what's needed to have HEIC preview support in preview generator app?**

**Comment by bcutter** [comment]
Edit: initial HEIC preview could be enabled following https://help.nextcloud.com/t/solved-image-previews-only-working-for-heic-photos/164302/8. According to https://github.com/nextcloud/server/pull/28079 it has been disabled by default because of https://hackerone.com/reports/1261413. Manually re-enabling it made HEIC previews to work at all - for live preview generation, which creates quite some load on the server.

Now curious to see if preview generator app can/will render HEIC files too as it has been enabled in `config.php`.

**Comment by st3iny** [comment]
All steps required to enable preview generation for HEIC/HEIF are documented here: https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#previews
Please not the big orange warning box about extra steps that are required to enable HEIC previews.

I'll close the issue as this is not related to the previewgenerator app.

Compiling Imaginary from source or using it directly is discouraged. We provide an up-to-date docker image at `docker.io/nextcloud/aio-imaginary:latest`. Unfortunately, the official project and docker image seem unmaintained at the moment.

**Comment by bcutter** [comment]
Initial support already described in my previous post. Open questions (as I still doubt preview generation with this project works for HEIC):

> Is there a way to synthetically test if preview generator app actually creates HEIC image previews now?
> Therefore: is there a need to re-generate previews for all existing images now?

**Comment by st3iny** [comment]
You can upload a new photo, run pre-generate and check if there is a preview in your browser.

**Comment by st3iny** [comment]
Regarding the second question: I fear you have to generate all previews again by doing the initial generation. Old files won't be picked up by `pre-generate` until they are rewritten. You could narrow it down by providing paths to `generate-all`.

**Comment by bcutter** [comment]
> We provide an up-to-date docker image at `docker.io/nextcloud/aio-imaginary:latest`. Unfortunately, the official project and docker image seem unmaintained at the moment.

Just to make sure: the "NC-Imaginary" Docker container is working standalone, so it's possible to use that container without running NC off the complete AIO suite, isn't it?

I only want to use Imaginary and keep the rest of NC installed bare metal. Otherwise I'd need to run the (pretty old) official Imaginary docker image.
