### ISSUE TITLE
`preview:pre-generate` ignores `.nomedia` in ancestor folders of the added/modified folder

### ISSUE THREAD

**Issue by th0rgall** [nextcloud/previewgenerator#433]
## Context

I have an WebDAV External Storage with pictures, say `ExternalPhotos`. The root folder of this storage has a `.nomedia` file. The folders in the storage are organized by `YYYY/MM`.

I added a folder 01 to 2021, and then ran `./occ preview:generate-all`.

This lead to the expected behavior, the 2021/01 folder was skipped, because the root `ExternalPhotos` was skipped. Log file entry:
```
2023-11-30T09:51:11+00:00 Skipping folder /thor/files/ExternalPhotos
```

## Problem

Afterwards, I ran `./occ preview:pre-generate`. Now it _unexpectedly_ started indexing 2021/01 on the external storage.

```
...
2023-11-30T11:46:10+00:00 Generating previews for  /thor/files/ExternalPhotos/2021/01/IMG_001.HEIC
...
```

I presume that this is due to the difference in the behavior commands:
- likely `generate-all` does a full top-down scan of the Nextcloud instance directory tree, and therefore notices the `.nomedia` in `ExternalStorage`
- likely `pre-generate` does _not_ attempt a full scan, but only looks at the log of modified/added directories since the last time it ran (there are some hints about this in the README/info about this app). Since `ExternalStorage/2021/01` was added, it would only check for `ExternalStorage/2021/01/.nomedia`, and not for `ExternalStorage/.nomedia` or `.nomedia` files in any other ancestral folder.

## Workaround

This suspicion was further confirmed when I added .nomedia files to `2021` and `2021/01`. Now, `pre-generate` didn't attempt to generate the previews anymore.

## Solution?

Is my suspecion about this (for me) unexpected behavior correct?

If so, I think it would be nice if `pre-generate` scanned all ancestor folders of modified folders for `.nomedia` files, and not just the folder itself. That would make it behave as I expect.

**Comment by st3iny** [comment]
Thank you for the detailed analysis! I already have a suspicion what is broken and will try to investigate.

**Comment by astro-1999** [comment]
Any update on this issue?  I have had to disable the app and miss it.

**Comment by NeilSauv** [comment]
Still no fix ? This is a very annoying problem.
