### ISSUE TITLE
Make Previews progressive

### ISSUE THREAD

**Issue by VilterPD** [nextcloud/previewgenerator#444]
I recently added an optimization script, but found the overwhelming advantage would come from making previews progressive. Depending on what is being used to compress images, this could probably done with a single argument. Anyone up to that?

**Comment by st3iny** [comment]
This is an interesting idea.

It has to be implemented in https://github.com/nextcloud/server though, as the actual generation logic is handled there.

**Comment by VilterPD** [comment]
I have added it here: [https://github.com/nextcloud/server/issues/43458](https://github.com/nextcloud/server/issues/43458)

**Comment by joshtrichards** [comment]
Closing since this since it's being tracked in nextcloud/server#43458 and presently there's nothing to do in the `previewgenerator` app.
