### ISSUE TITLE
Preview photos as negatives

### ISSUE THREAD

**Issue by nordscan** [nextcloud/previewgenerator#450]
After update and fresh install too

**Operating system:** Linux 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64

**Webserver:** Apache/2.4.58 (Unix) (fpm-fcgi)

**Database:** pgsql PostgreSQL 15.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit

**Nextcloud version**: 28.0.2 - 28.0.2.5

**Nextcloud** AIO v7.12.1

**Apps**:

Enabled:
 - activity: 2.20.0
 - admin_audit: 1.18.0
 - calendar: 4.6.5
 - circles: 28.0.0-dev
 - cloud_federation_api: 1.11.0
 - comments: 1.18.0
 - contacts: 5.5.1
 - contactsinteraction: 1.9.0
 - dashboard: 7.8.0
 - dav: 1.29.1
 - deck: 1.12.2
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_fulltextsearch: 28.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - fulltextsearch: 28.0.0
 - fulltextsearch_elasticsearch: 28.0.0
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - memories: 6.2.2
 - nextcloud-aio: 0.4.0
 - nextcloud_announcements: 1.17.0
 - notes: 4.9.2
 - notifications: 2.16.0
 - notify_push: 0.6.9
 - oauth2: 1.16.3
 - password_policy: 1.18.0
 - photos: 2.4.0
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recognize: 6.0.1
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.1
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - support: 1.11.0
 - survey_client: 1.16.0
 - systemtags: 1.18.0
 - tasks: 0.15.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - twofactor_totp: 10.0.0-beta.2
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - bruteforcesettings
 - encryption
 - facerecognition
 - files_external
 - files_rightclick: 1.6.0
 - suspicious_login
 - user_ldap

Fresh installation of Nextcloud AIO and some default and all new photos (photos and memories app) in preview showed as negative, when i download it they are fine…

![image](https://github.com/nextcloud/previewgenerator/assets/25382868/514d66ac-64a6-426d-8c1d-0ecbc2e47793)

![image](https://github.com/nextcloud/previewgenerator/assets/25382868/466e2be1-351b-441b-98d3-0922ad045eff)

**Comment by st3iny** [comment]
Are you using the built-in imaginary preview provider of AIO?

**Comment by nordscan** [comment]
this was built-in, clean instal - first start.
I use now instead `latest` image this one: `nextcloud/all-in-one:20240201_120631-latest` and it works without any issues

**Comment by st3iny** [comment]
I'm glad to hear that it's working again. I'll close this issue as you were able to resolve it.

**Comment by st3iny** [comment]
Thanks for linking the other issue. Let's continue the discussion there.
