### ISSUE TITLE
Video thumbnails not generated :'( 

### ISSUE THREAD

**Issue by vianmora** [nextcloud/previewgenerator#473]
Hello, sorry, i know there's a lot of posts in the nextcloud forum about this topic, but i'm a bit lost :/ 

I wanted to show preview of my videos in nextcloud : 

![image](https://github.com/nextcloud/previewgenerator/assets/34892879/c9c37823-97cc-4c08-9766-9ae47340edb8)

so i installed previewgenerator and ffmpeg

i have no root access, so i've put the absolute path of ffmpeg into my config.php file. 

It look like this :

```
  'preview_max_x' => 256,
  'preview_max_y' => 256,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\Movie',
    2 => 'OC\\Preview\\PNG',
    3 => 'OC\\Preview\\JPEG',
    4 => 'OC\\Preview\\GIF',
    5 => 'OC\\Preview\\BMP',
    6 => 'OC\\Preview\\XBitmap',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\MP4',
    9 => 'OC\\Preview\\TXT',
    10 => 'OC\\Preview\\MarkDown',
    11 => 'OC\\Preview\\PDF',
    12 => 'OC\\Preview\\MSOfficeDoc',
    13 => 'OC\\Preview\\HEIC',
    14 => 'OC\\Preview\\MKV',
    15 => 'OC\\Preview\\AVI',
    16 => 'OC\\Preview\\MOV',
  ),
  'preview_ffmpeg_path' => '/homepages/45/d317196559/htdocs/nextcloud/nextcloud/ffmpeg/ffmpeg-git-20240301-amd64-static/ffmpeg',
  'jpeg_quality' => '60',
  'ffmpeg' => '/homepages/45/d317196559/htdocs/nextcloud/nextcloud/ffmpeg/ffmpeg-git-20240301-amd64-static/ffmpeg',
```

I've also set  `heightSizes`, `squareSizes` and `widthSizes` to limit the number of preview generated

I'v laucnhed the generation for my folder : 
`occ preview:generate-all --path='/user_test/files/photos/tests' -vvv`

but in preview, the folder created are empty :'( 

And know, i'm a little bit lost, nothing seems to work ^^ 
Is there something i did wrong please ? 

Sorry to bother you with this :'(

Thank you for your answer !

**Comment by st3iny** [comment]
Please check the nextcloud log files for errors. It looks like there is something wrong with the generation or ffmpeg.

**Comment by joshtrichards** [comment]
>  i know there's a lot of posts in the nextcloud forum about this topic, but i'm a bit lost :/

Hi @vianmora - Can you please post your query on the Help Forum (https://help.nextcloud.com)? That's a more suitable place for this sort of query. 

This is a bug reporting channel. We can't provide free technical support here while also having time to address legitimate bug reports.

Thanks!
