### ISSUE TITLE
Preview: Exception thrown: OCP\Files\GenericFileException

### ISSUE THREAD

**Issue by lxto** [nextcloud/previewgenerator#475]
After upgrading Nextcoudpi to ncp 1.54.0  and Debian-Bookworm, php v. 8.3 i get this issue.
Preview generation stops working. Deleting and reinstalling Preview-Generator did not change anything.
What can i do?

Nextcloud Log says:

>[index] Fehler: Exception thrown: OCP\Files\GenericFileException
	GET /index.php/apps/photos/api/v1/preview/607191?etag=dc7cb9be6503ddf04a03509df8126e94&x=512&y=512
	von 192.168.1.80 von lxto um 07.05.2024, 08:07:12

After executing preview from "ncp-config" > "Tools" manually CLI says:
>`preview:pre-generate
[OCP\Exceptions\AppConfigUnknownKeyException]  
  unknown config key                             
                                                 
>Exception trace:
  at /var/www/nextcloud/lib/private/AppConfig.php:203
 OC\AppConfig->isLazy() at /var/www/nextcloud/lib/private/AppConfig.php:829
 OC\AppConfig->setTypedValue() at /var/www/nextcloud/lib/private/AppConfig.php:1358
 OC\AppConfig->setValue() at /var/www/nextcloud/lib/private/AllConfig.php:208
 OC\AllConfig->setAppValue() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:216
 OCA\PreviewGenerator\Command\PreGenerate->setPID() at /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php:105
 OCA\PreviewGenerator\Command\PreGenerate->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:213
 OC\Console\Application->run() at /var/www/nextcloud/console.php:113
 require_once() at /var/www/nextcloud/occ:11

**Comment by st3iny** [comment]
I'm sorry but I can't provide support for Nextcloud Pi. You could at least specify the version of Nextcloud that is installed.

**Comment by lxto** [comment]
oh, sorry i forgot, it is NC 29.0
