### ISSUE TITLE
"Encryption is enabled. Aborted." on unencrypted folder

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/previewgenerator#481]
# System
NC 28.0.6
previewgenerator: 5.5.0

# Problem
I have the encryption app enabled but don't encrypt local directories. Only data in remote folders is encrypted.
I try to run occ preview:generate-all but get "Encryption is enabled. Aborted."

# Proposed solution
Instead of testing if the encryption *app* is enabled, previewgenerator should ideally test if the folder it is looking at is actually encrypted and if so, just skip that folder.

**Comment by i--storm** [comment]
Dame problem even if I disable encryption app.

**Comment by st3iny** [comment]
Yeah, the app currently checks if encryption is enabled globally on the server instead of checking individual files and folders.

The feature request to improve this is at: https://github.com/nextcloud/previewgenerator/issues/156

I'm closing in favor of the other issue.
