### ISSUE TITLE
Prevent previews for external storages

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/previewgenerator#490]
I have several external shares connected to the NC and there are a large number of photos on them (about 1 Tb). This is something like an archive storages. As a result of connecting these shares, over time I ended up with a large number of inodes with previews, which slows down the server. Seems it should be some kind of option that will prohibit generating previews for external shares.

**Comment by st3iny** [comment]
What exactly do you mean by external shares? Is it an external storage mounted into your Nextcloud or an incoming share from another Nextcloud server?

**Comment by intervisionlord** [comment]
> What exactly do you mean by external shares? Is it an external storage mounted into your Nextcloud or an incoming share from another Nextcloud server?

I mean external storage like FTP

**Comment by joshtrichards** [comment]
I thought we already did this? i.e. see #190 :thinking:

**Comment by intervisionlord** [comment]
Oh, seems so. Sorry

> I thought we already did this? i.e. see #190 🤔
