### ISSUE TITLE
is './occ preview:generate-all' idempotent?

### ISSUE THREAD

**Issue by oucil** [nextcloud/previewgenerator#496]
Hi there, just looking for an answer to whether `./occ preview:generate-all` is idempotent? 

I have my NC and modules installed and upgraded by ansible scripts, and on a fresh upgrade the script will call the `generate-all` whether or not the plugin was installed previously or not. I'm just curious if the script is smart enough to see that previews of existing images already exist, or whether it tries to rebuild ALL of the previews anyway.

Thanks,
Kevin.

**Comment by Forza-tng** [comment]
@oucil If a preview already exists, previewgenerator skips it.

**Comment by st3iny** [comment]
What @Forza-tng said. It will still iterate all files and folders but will skip previews which are already present.
