### ISSUE TITLE
Add a verbose switch to "preview:pre-generate" OR why is "preview:pre-generate" taking longer than "preview:generate-all"?

### ISSUE THREAD

**Issue by tatl-im** [nextcloud/previewgenerator#517]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
29.0.7

**Is your feature request related to a problem? Please describe.**
I've run preview:generate-all once, which took hours. When I run it again, it takes about 3 minutes because the previews have been generated.
My problem is, when I run preview:pre-generate, it has been running for 35 minutes and counting, with no shell output. preview:pre-generate is taking much longer than preview:generate-all and I don't know why.

**Describe the solution you'd like**
If preview:pre-generate had verbose switches like preview:generate-all, i.e. -v -vv -vvv, then I would have a better handle as to why it's taking so long.

**Describe alternatives you've considered**
I've tried using -v -vv and -vvv switches on preview:pre-generate, but it produced no output.

**Additional context**

**Comment by st3iny** [comment]
This is already implemented.

No output means that there are no files being processed. If you pass `-vvv` it will log a line for each processed files.

Please check if the `-vvv` switch might be eaten by your wrapper (e.g. `docker exec ...`). Use the `--` parameter to prevent all further arguments to be processed by the outer wrapper in this case.

**Comment by tatl-im** [comment]
I mean, I can't recreate the original problem where generate-all ran for hours with no output, so sure I guess.
